### ISSUE TITLE
Greek characters in attributes not properly displayed in Jupyter notebooks

### ISSUE THREAD

**Issue by ifenty** [pydata/xarray#5035] opened 2021-03-14 23:35 UTC
**What happened**:

Some "latex" like symbols are not rendered properly when DataArray *attributes* are rendered in Jupyter notebooks. Jupyter notebooks can render simple latex.  For instance, a markdown cell with the following gives the expected result

```
$\rho \int_0^1 x$
```

However, when the same text is used in a DataArray attribute, and the DataArray is "displayed" in the Jupyter notebook, the greek letters are not rendered.  However, the integral and x are rendered.

**What you expected to happen**:

I expected the latex greek symbols in xarray DataArray attributes to be rendered properly, just like other latex.

**Minimal Complete Verifiable Example**:

In a regular 'Code' cell
```
tmp = xr.DataArray(1)
tmp.attrs['comment_1'] = '$\rho$'
tmp.attrs['comment_2'] = '$\int_0^1 x$'
tmp
```

the comment_1 is rendered as "ho" while the comment_2 is rendered properly

**Anything else we need to know?**:

My real example looks more like this:

```python in Code cell in Jupyter Notebook
ecco_field = xr.DataArray(1)
ecco_field.name = 'THETA'
ecco_field.attrs['comment'] = 'Sea water potential temperature is the temperature a parcel of sea water would have if moved adiabatically to sea level pressure. Note: the equation of state is a modified UNESCO formula by Jackett and McDougall (1995), which uses the model variable potential temperature as input assuming a horizontally and temporally constant pressure of $p_0=-g \rho_{0} z$.'
```

If the ```ecco_field``` variable is then examined, the final equation is rendered "p0 = -g ho_0 z",  -- the "$\rho$" is missing
**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-957.21.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.6.2

xarray: 0.16.1
pandas: 1.1.3
numpy: 1.19.2
scipy: 1.5.3
netCDF4: 1.5.1.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.30.0
distributed: 2.30.0
matplotlib: 3.3.2
cartopy: 0.18.0
seaborn: None
numbagg: None
pint: None
setuptools: 49.6.0.post20201009
pip: 20.2.4
conda: None
pytest: 6.2.2
IPython: 7.18.1
sphinx: 3.3.0
</details>

**Comment by keewis** [comment] 2021-03-14 23:39
I think that's because of how python treats escape codes: `\r` is a existing escape code while `\i` is not. If you don't want the escape codes you can either escape the backslash: `"$\\rho$"` or use "raw" strings: `r"$\rho$"`.

**Comment by max-sixty** [comment] 2021-03-15 04:16
Confirmed that using `r'$\rho$'` prints `𝜌`

**Comment by ifenty** [comment] 2021-03-15 04:32
This is helpful.  How does Jupyter notebook "know" how to display and format the contents of xarray objects?  Could there be an intervention at at the display stage?  Could the the contents of attributes that are wrapped double $ be assumed to be latex and automatically wrapped in the r'  ' that @max-sixty reports on?
 

These "latex-like" comments are going to NetCDF files. Users *may* use Python but need not.  People tend to recognize latex formatted equations and I'd like to avoid 'python-specific' escape acrobatics in the comment field because they could add confusion.

**Comment by max-sixty** [comment] 2021-03-15 04:43
I don't think this is actually driven by xarray or jupyter, or even python printing — it's that python is escaping the string when it's set. So using raw strings sets it correctly.

```python
In [1]: x = '$\rho$'

In [2]: print(x)
ho$

In [4]: print([c for c in x])
['$', '\r', 'h', 'o', '$']

In [5]: x = r'$\rho$'

In [6]: print([c for c in x])
['$', '\\', 'r', 'h', 'o', '$']
```

**Comment by max-sixty** [comment] 2021-03-15 04:44
Though the second character is a printing issue! It's actually a `\`

```python

In [8]: print(x[1])
\
```

**Comment by keewis** [comment] 2021-03-15 15:30
to be clear, [escape sequences](https://en.wikipedia.org/wiki/Escape_sequence) are not something unique to python, they are a way to specify unprintable (or untypable) characters in source code. For example, in C you would do something like
```c
const char *string = "$\\rho$";
```
which will give you a string containing the characters `$`, `\`, `r`, `h`, `o`, and `$`.

Once you have the correct string there is nothing else you have to do, the data will not be modified.

**Comment by keewis** [comment] 2021-03-15 15:31
closing, but feel free to reopen if you have more questions.

**Closed by keewis** 2021-03-15 15:31 UTC
