### ISSUE TITLE
IPython auto-completion triggers data loading

### ISSUE THREAD

**Issue by benbovy** [pydata/xarray#1727] opened 2017-11-18 00:14 UTC
I create a big netcdf file like this:

```python
In [1]: import xarray as xr

In [2]: import numpy as np

In [3]: ds = xr.Dataset({'myvar': np.arange(100000000, dtype='float64')})

In [4]: ds.to_netcdf('test.nc')

```

Then when I open the file in a IPython console and I use auto-completion, it triggers loading the data.

```python
In [1]: import xarray as xr

In [2]: ds = xr.open_dataset('test.nc')

In [3]: ds.my     # <TAB> autocompletion with any character -> triggers loading
``` 

I don't have that issue using the python console. Auto-completion for dictionary access in IPython (#1632) works fine too.

#### Output of ``xr.show_versions()``

<details>
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: fr_BE.UTF-8
LOCALE: fr_BE.UTF-8

xarray: 0.10.0rc1-2-gf83361c
pandas: 0.21.0
numpy: 1.13.1
scipy: 0.19.1
netCDF4: 1.3.1
h5netcdf: 0.5.0
Nio: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.15.4
matplotlib: None
cartopy: None
seaborn: None
setuptools: 36.6.0
pip: 9.0.1
conda: None
pytest: None
IPython: 6.2.1
sphinx: None

</details>

**Comment by fujiisoup** [comment] 2017-11-18 01:17
Your `xr.Dataset` consists only from a single coordinate variable
```python
<xarray.Dataset>
Dimensions:  (myvar: 100000000)
Coordinates:
  * myvar    (myvar) float64 0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 ...
Data variables:
    *empty*
```
(This behavior is somehow confusing...)

In `xarray`, coordinate variables are always loaded into memory.

The following example works well

```python
In [1]: import xarray as xr
   ...: import numpy as np
   ...: ds = xr.Dataset({'myvar': (('x', 'y'), np.arange(100000000).reshape(1000
   ...: , 100000))},
   ...:                 coords={'x': np.arange(1000)})
   ...: ds.to_netcdf('test.nc')
   ...: 

In [2]: ds_on_disk = xr.open_dataset('test.nc')
   ...: ds_on_disk['myvar'].variable._in_memory
   ...: 
Out[2]: False

In [3]: ds_on_disk.my  # -> [Tab]
In [3]: ds_on_disk.myvar.variable._in_memory
   ...: 
Out[3]: False

In [4]: ds_on_disk['x'].variable._in_memory
Out[4]: True
```

**Comment by benbovy** [comment] 2017-11-18 01:37
Sorry my example above was wrong. In the example below `myvar` is not a coordinate, but it still triggers data loading when pressing tab generally (not only trying to auto-complete `myvar`).  

```
In [1]: import xarray as xr

In [2]: ds = xr.open_dataset('test.nc')

In [3]: ds
Out[3]: 
<xarray.Dataset>
Dimensions:  (x: 1000000000)
Dimensions without coordinates: x
Data variables:
    myvar    (x) float64 ...

In [4]: ds['myvar']
Out[4]: 
<xarray.DataArray 'myvar' (x: 1000000000)>
[1000000000 values with dtype=float64]
Dimensions without coordinates: x

In [5]: ds['myvar'].variable._in_memory
Out[5]: False

In [6]: ds.anything     # pressed [Tab] and then [Enter]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-5e7144cb0cd3> in <module>()
----> 1 ds.anything

~/GitRepos/xarray_dev/xarray/core/common.py in __getattr__(self, name)
    174                     return source[name]
    175         raise AttributeError("%r object has no attribute %r" %
--> 176                              (type(self).__name__, name))
    177 
    178     def __setattr__(self, name, value):

AttributeError: 'Dataset' object has no attribute 'anything'

In [7]: ds['myvar'].variable._in_memory
Out[7]: True
```

Unless I miss something obvious (it's late), this is weird.

**Comment by fujiisoup** [comment] 2017-11-18 01:45
Thanks. 
This is reproduced also in my environment.
It's strange ...
Tagged as a bug.

**Comment by shoyer** [comment] 2017-11-18 01:52
We have a unit test `test_lazy_load` in `test_dataset.py` that is probably a good place to start on the test case for this.

**Comment by fujiisoup** [comment] 2017-11-18 02:22
I found this happens with IPython=6.1.0, but does not with IPython=5.1.0.
Maybe it is the upstream issue.

But if we can avoid within xarray, it would be great,

**Comment by benbovy** [comment] 2017-11-18 02:26
I've been investigating a bit, and actually in the example above the data may be loaded + duplicated!

in `Dataset._item_sources` ([this line](https://github.com/pydata/xarray/blob/6463504ae7c6fd0c2250237a2a74baf1b707723a/xarray/core/dataset.py#L807)), the item `{d: self[d] for d in self.dims}` computes the DataArray, `ds['x']`, which has the same (huge) size than `myvar`.

Still don't know exactly why the data of `myvar` is loaded (maybe something indeed related to the use in IPython 6.x of a more advanced completion system based on `jedi`).

**Comment by fujiisoup** [comment] 2017-11-18 06:39
It seems jedi's bug.

A minimal working example is
1. Save following as example.py
```python
import traceback

class ExampleClass(object):
    def __init__(self):
        pass

    @property
    def value(self):
        print('value called')
        print(traceback.print_exc())
```
2. In IPython, do
```python
In [1]: import example

In [2]: ex = example.ExampleClass()

In [3]: ex.val  -> press [Tab]
value called
Traceback (most recent call last):
None
KeyError: (('value',), frozenset())
  File "/home/keisukefujii/anaconda3/envs/tensorflow/lib/python3.5/site-packages/jedi/cache.py", line 119, in wrapper
    return dct[key]
  File "/home/keisukefujii/anaconda3/envs/tensorflow/lib/python3.5/site-packages/jedi/cache.py", line 46, in wrapper
    return getattr(self, name)
value called
None
AttributeError: 'CompiledName' object has no attribute '_infer'
Traceback (most recent call last):
```

**Comment by shoyer** [comment] 2017-11-18 06:57
See here for the IPython issue: https://github.com/ipython/ipython/issues/10720

**Comment by fujiisoup** [comment] 2017-11-18 07:01
Thanks @shoyer .
I think I should close the issue in jedi.

**Comment by shoyer** [comment] 2017-11-18 07:02
It looks like this may already be fixed upstream. As suggested in https://github.com/ipython/ipython/issues/10521, updating to Jedi 0.11 seems to fix the issue.

**Comment by fujiisoup** [comment] 2017-11-18 07:09
@shoyer 
Thanks. Confirmed.
Closing.

**Closed by fujiisoup** 2017-11-18 07:09 UTC
