### ISSUE TITLE
Roundtripping between a dimension coordinate and scalar coordinate on a Dataset

### ISSUE THREAD

**Issue by spencerkclark** [pydata/xarray#2856] opened 2019-03-31 13:42 UTC
#### Code Sample, a copy-pastable example if possible

In xarray 0.12.0 the following example produces a Dataset with no indexes:
```
In [1]: import xarray as xr

In [2]: da = xr.DataArray([1], [('x', [0])], name='a')

In [3]: da.to_dataset().isel(x=0).expand_dims('x').indexes
Out[3]:
```

#### Expected Output

In xarray 0.11.3 the roundtrip sequence above properly recovers the initial index along the `'x'` dimension:
```
In [1]: import xarray as xr

In [2]: da = xr.DataArray([1], [('x', [0])], name='a')

In [3]: da.to_dataset().isel(x=0).expand_dims('x').indexes
Out[3]: x: Int64Index([0], dtype='int64', name='x')
```

#### Output of ``xr.show_versions()``

<details><p>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.1
libnetcdf: 4.6.1

xarray: 0.12.0
pandas: 0.24.2
numpy: 1.13.1
scipy: 0.19.1
netCDF4: 1.4.0
pydap: None
h5netcdf: 0.5.1
h5py: 2.8.0
Nio: None
zarr: None
cftime: 1.0.0
nc_time_axis: None
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.2.0
dask: 0.17.5
distributed: 1.21.8
matplotlib: 2.0.2
cartopy: None
seaborn: None
setuptools: 40.5.0
pip: 9.0.1
conda: None
pytest: 3.10.0
IPython: 6.4.0
sphinx: 1.7.4
```

</p></details>

**Comment by rabernat** [comment] 2019-03-31 15:01
Possible duplicate of #2842? Seems awfully similar.

**Comment by spencerkclark** [comment] 2019-03-31 15:11
This problem persists with the master version of xarray, so while it may be related, it was not fixed by #2845.

**Comment by shoyer** [comment] 2019-03-31 17:12
This  is similar to #2842 in that it was  also introduced by https://github.com/pydata/xarray/pull/2696. Apparently I need to be more diligent about testing these changes :).

**Comment by shoyer** [comment] 2019-03-31 21:48
see https://github.com/pydata/xarray/pull/2858

**Closed** 2019-04-04 21:58 UTC
