### ISSUE TITLE
0.13.0 release

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#3257] opened 2019-08-23 21:04 UTC
What do we think about a minor release soon?

My colleague just hit https://github.com/pydata/xarray/pull/3145 which reminded me the current release can make filing an issue confusing for folks

We've had a v good pipeline of changes in just a month: https://github.com/pydata/xarray/blob/master/doc/whats-new.rst#L18

I'm happy to help with this; ref https://github.com/pydata/xarray/issues/2998#issuecomment-516218628

**Comment by shoyer** [comment] 2019-08-24 03:53
There are couple of small fixes for sparse arrays with open pull requests. I would lean toward getting those in before the release.

One thing that would be especially helpful is finalizing some deprecations that have been open for a while, e.g., the removal of the inplace argument and sel_points().

**Comment by shoyer** [comment] 2019-08-24 03:54
Also it would be great if you’d like to try going through the release process. We can potentially automate and/or remove some of those steps.

**Comment by crusaderky** [comment] 2019-08-27 08:32
Given that's 1 hour of work about once a month... Unless there is appetite for increasing the release frequency, I would say automation is overkill

**Comment by dcherian** [comment] 2019-08-27 14:48
```
 4. On the master branch, commit the release in git:
      git commit -a -m 'Release v0.X.Y'
 5. Tag the release:
      git tag -a v0.X.Y -m 'v0.X.Y'
 6. Build source and binary wheels for pypi:
      git clean -xdf  # this deletes all uncommited changes!
      python setup.py bdist_wheel sdist
 7. Use twine to register and upload the release on pypi. Be careful, you can't
    take this back!
      twine upload dist/xarray-0.X.Y*
    You will need to be listed as a package owner at
    https://pypi.python.org/pypi/xarray for this to work.
 8. Push your changes to master:
      git push upstream master
      git push upstream --tags
 9. Update the stable branch (used by ReadTheDocs) and switch back to master:
      git checkout stable
      git rebase master
```

This bit seems easily scriptable

**Comment by dcherian** [comment] 2019-08-27 17:55
> I find it very nice that I make a new release on GitHub and packages appear on PyPI and the web docs are automatically updated to the new version.

How do you do this? i.e. trigger PyPI and RTD updates with a tag on github?

**Comment by max-sixty** [comment] 2019-08-29 17:08
FYI re RTD PR feature, too many PRs! :)

> We are sorry, we can't enable the pull requests builder feature for your project right now. This is because the long build time and many active PRs of your project. We have limited resources, we are working in making the builds faster. We let you know when we can enable the feature for your project.

**Comment by fmaussion** [comment] 2019-08-30 10:07
RTD is struggling with resources, and I can understand that. What is really annoying (and the problem is often the same on travis) is that the conda install is taking a huge part of the build process resources. See e.g. https://github.com/readthedocs/readthedocs.org/issues/6025 , where I ended up using pip for very satisfying results (!).

**Comment by crusaderky** [comment] 2019-08-30 10:17
Can't we have a nightly build of docker images with all the xarray depencencies?
Then the individual CI jobs would literally become something like
```
FROM xarray-ci-py37
RUN pip install .
```

**Comment by fmaussion** [comment] 2019-08-30 10:27
> Can't we have a nightly build of docker images with all the xarray depencencies?

This would help on Travis yes, but not on RTD who doesn't support docker. But otherwise yes, I've also found that CI is faster and more reliable with docker. In terms of resources "in general", I wonder if it wouldn't be nice to share a common testing image base with other packages of the pydata ecosytem.

**Comment by shoyer** [comment] 2019-09-04 17:00
I did some searching for "FutureWarning" and "DeprecationWarning", and turned up a bunch worth cleaning up for 0.13:
https://github.com/pydata/xarray/issues/3280

Otherwise I think we're ready do a release?

**Comment by max-sixty** [comment] 2019-09-05 04:22
(FYI I am on vacation — can contribute next week)

**Comment by dcherian** [comment] 2019-09-05 06:02
It would be nice to get #3239 in since it fixes a longstanding issue with open_mfdataset.

**Comment by dcherian** [comment] 2019-09-07 19:53
We should also merge the `scipy19-docs` branch since that has some nice changes (ping @rabernat).

**Comment by rabernat** [comment] 2019-09-10 20:49
> We should also merge the `scipy19-docs` branch since that has some nice changes

Ideally there are a few things we should finish:
- #3199 - GRIB / ECMWF example for gallery
- #3131 - My own tutorial on merging / combining datasets

I agree it would be nice to get these into a release. On the other hand, I feel like most doc users are just looking at the "latest" docs, so perhaps not as urgent as the other items on here.

**Comment by dcherian** [comment] 2019-09-10 20:56
> On the other hand, I feel like most doc users are just looking at the "latest" docs

I'm not so sure of this. The default is stable. and it isn't very obvious how to change it.

We can also merge that branch multiple times...

**Comment by shoyer** [comment] 2019-09-10 21:15
Yes, we can merge/rebase changes into "stable" even after cutting a release.

**Comment by max-sixty** [comment] 2019-09-17 14:41
Anything final remaining? A couple of nice-to-haves on https://github.com/pydata/xarray/issues/3280 but otherwise I think all done?

If so, I have some time this week to help—I can coordinate

**Comment by dcherian** [comment] 2019-09-17 15:06
Yes we should release ASAP. #3313 and #3314 are the last two items on the checklist.

**Comment by shoyer** [comment] 2019-09-17 16:09
OK, @max-sixty or @dcherian do one of you want to take the lead on issuing the release this time? Everything *should* be in the `HOW_TO_RELEASE` checklist, but I'm sure something will come up -- nonetheless, it's good to increase the bus factor!

**Comment by dcherian** [comment] 2019-09-17 17:31
OK happy to do so.

>  You will need to be listed as a package owner at
    https://pypi.python.org/pypi/xarray for this to work.

Do you want to add the rest of the core team as owners on pypi and RTD?

**Comment by max-sixty** [comment] 2019-09-17 18:01
Great—happy to help @dcherian—thank you!

**Comment by dcherian** [comment] 2019-09-17 19:39
OK I've done everything but
- [ ] upload to PyPI
- [ ] update RTD
- [ ] announcement email

@max-sixty Can you take over emailing the users list?
> 14. Issue the release announcement! For bug fix releases, I usually only email
    xarray@googlegroups.com. For major/feature releases, I will email a broader
    list (no more than once every 3-6 months):
      pydata@googlegroups.com, xarray@googlegroups.com,
      numpy-discussion@scipy.org, scipy-user@scipy.org,
      pyaos@lists.johnny-lin.com
    Google search will turn up examples of prior release announcements (look for
    "ANN xarray").

**Comment by dcherian** [comment] 2019-09-17 19:39
@shoyer instructions in HOW_TO_RELEASE worked perfectly :)

**Comment by shoyer** [comment] 2019-09-17 20:17
@dcherian (and anyone else who's interested) could you please send me your pypi and RTD account names?

**Comment by max-sixty** [comment] 2019-09-17 20:22
Yes, and our Twitter account! Ping back when it's on PyPI and I'll send out

**Comment by max-sixty** [comment] 2019-09-17 20:25
@shoyer I'm at maximilianroos on PyPI but maybe we lock that down tighter than the GH privileges?

**Comment by shoyer** [comment] 2019-09-17 20:34
Maintainers permissions enable: "Can upload releases for a package. Cannot add collaborators. Cannot delete files, releases, or the project."

I'm pretty happy passing that out to anyone interested :)

**Comment by dcherian** [comment] 2019-09-17 20:36
Hahaha, I just signed up at PyPI as dcherian

**Comment by shoyer** [comment] 2019-09-17 21:08
@dcherian done! you should have permissions for both RTD and pypi now

**Comment by dcherian** [comment] 2019-09-17 21:13
Thanks! Done with release on PyPI: https://pypi.org/project/xarray/0.13.0/

Time to announce!

**Comment by max-sixty** [comment] 2019-09-17 21:59
@dcherian did you add a tag? I don't see that yet

**Comment by dcherian** [comment] 2019-09-17 22:12
https://github.com/pydata/xarray/releases/tag/v0.13.0 ?

**Comment by max-sixty** [comment] 2019-09-17 22:20
Great! My mistake

**Comment by jhamman** [comment] 2019-09-17 23:36
I just merged https://github.com/conda-forge/xarray-feedstock/pull/50, so the release should be available on conda-forge soon.

**Closed** 2019-09-18 01:33 UTC

**Comment by shoyer** [comment] 2019-09-18 02:00
Success! Thanks team!

**Comment by max-sixty** [comment] 2019-09-18 02:12
@pydata/xarray let me know any feedback on the email announcements
