### ISSUE TITLE
expand_dims changes attrs and encoding of coordinate variable

### ISSUE THREAD

**Issue by jfpiolle** [pydata/xarray#3819] opened 2020-03-02 14:33 UTC
Expanding the dimensions of a variable with a dimension having the same name as a coordinate variable will also change the attributes (including encoding attributes) of this coordinate variable!

The following examples prints the attrs and encoding of coordinate variable ``time`` before/after expanding the dimensions of the variable ``sea_surface_temperature``

```python
import xarray as xr
import numpy as np


grid = xr.Dataset({
    'time': (('time',), [np.datetime64('2018-01-01')]),
    'lat': (('lat'), np.arange(-80, 80, 1)),
    'lon': (('lon',), np.arange(-180, 180, 1)),
    'sea_surface_temperature': (('lat', 'lon',), np.ones(shape=(160, 360)))
    })

grid['time'].encoding['units'] = 'seconds since 1981-01-01 00:00:00'
grid['time'].attrs['comment'] = 'some comment'

print(grid['time'].encoding, grid['time'].attrs)
grid['sea_surface_temperature'] = grid['sea_surface_temperature'].expand_dims('time', axis=0)
print(grid['time'].encoding, grid['time'].attrs)

```
The current output is:

```
{'units': 'seconds since 1981-01-01 00:00:00'} {'comment': 'some comment'}
{} {}
```

#### Expected Output

I would not expect any change to other coordinates or variables than the expanded one (here ``sea_surface_temperature``)

```
{'units': 'seconds since 1981-01-01 00:00:00'} {'comment': 'some comment'}
{'units': 'seconds since 1981-01-01 00:00:00'} {'comment': 'some comment'}
```

#### Output of ``xr.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.8.1 (default, Jan  8 2020, 22:29:32) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.15.0-72-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8
LOCALE: fr_FR.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.7.3

xarray: 0.15.0
pandas: 1.0.1
numpy: 1.18.1
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.4.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.11.0
distributed: 2.11.0
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
setuptools: 45.2.0.post20200210
pip: 20.0.2
conda: None
pytest: None
IPython: None
sphinx: None

</details>

**Comment by dcherian** [comment] 2020-03-03 17:40
Thanks for the clear reproducible example @jfpiolle. I am marking this as a bug.

Are you up for fixing it?

**Comment by dcherian** [comment] 2020-04-06 22:52
There is a subtle error here:

```
>>> grid['sea_surface_temperature'].expand_dims('time', axis=0)
<xarray.DataArray 'sea_surface_temperature' (time: 1, lat: 160, lon: 360)>
array([[[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]]])
Coordinates:
  * lat      (lat) int64 -80 -79 -78 -77 -76 -75 -74 ... 73 74 75 76 77 78 79
  * lon      (lon) int64 -180 -179 -178 -177 -176 -175 ... 175 176 177 178 179
Dimensions without coordinates: time
```

`time` is added as an **unindexed** dimension with no `encoding` or `attrs` dicts. This is because once you pull the DataArray `sea_surface_temperature` out of the dataset; the `time` variable in the dataset is not attached to that DataArray (since it doesn't have a time dimension).

When the expanded dataarray is assigned back to the dataset, we run into #2180

The only solution I could find is 
```
grid["sea_surface_temperature"] = grid.sea_surface_temperature.expand_dims("time", axis=0).assign_coords(time=grid.time)
```

**Comment by dcherian** [comment] 2020-07-02 22:00
Please reopen if you have more questions.

**Closed by dcherian** 2020-07-02 22:00 UTC
Labels: bug
