### ISSUE TITLE
Xarray crashed on two computers with different reasons

### ISSUE THREAD

**Issue by forestbat** [pydata/xarray#7247] opened 2022-11-02 16:43 UTC
### What happened?

Before the error occured I have run this command on two computers：`pip install xarray[complete]`
But when I run my code:
```
import xarray as xa
cur_ds = xa.open_dataset(……)
```
IDEA on my first computer tells me: 
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\station-simulate\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\PC303\pyprojects\station-simulate\past_test.py", line 22, in <module>
    import xarray as xa
  File "C:\ProgramData\Anaconda3\envs\station-simulate\lib\site-packages\xarray\__init__.py", line 1, in <module>
    from . import testing, tutorial, ufuncs
  File "C:\ProgramData\Anaconda3\envs\station-simulate\lib\site-packages\xarray\tutorial.py", line 13, in <module>
    from .backends.api import open_dataset as _open_dataset
  File "C:\ProgramData\Anaconda3\envs\station-simulate\lib\site-packages\xarray\backends\__init__.py", line 9, in <module>
    from .h5netcdf_ import H5NetCDFStore
  File "C:\ProgramData\Anaconda3\envs\station-simulate\lib\site-packages\xarray\backends\h5netcdf_.py", line 25, in <module>
    from .netCDF4_ import (
  File "C:\ProgramData\Anaconda3\envs\station-simulate\lib\site-packages\xarray\backends\netCDF4_.py", line 33, in <module>
    import netCDF4
  File "C:\ProgramData\Anaconda3\envs\station-simulate\lib\site-packages\netCDF4\__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: DLL load failed while importing _netCDF4: 找不到指定的程序。
```
And on the 2nd computer, crash is this:
```
collecting ... Windows fatal exception: code 0xc0000139

Current thread 0x00002368 (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1176 in create_module
  File "<frozen importlib._bootstrap>", line 571 in module_from_spec
  File "<frozen importlib._bootstrap>", line 674 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\netCDF4\__init__.py", line 3 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\xarray\backends\netCDF4_.py", line 35 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\xarray\backends\h5netcdf_.py", line 27 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\xarray\backends\__init__.py", line 9 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 992 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\xarray\tutorial.py", line 16 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1078 in _handle_fromlist
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\xarray\__init__.py", line 1 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "C:\Users\k6789\IdeaProjects\station-simulate\past_predict.py", line 21 in <module>
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\assertion\rewrite.py", line 168 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<frozen importlib._bootstrap>", line 1050 in _gcd_import
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\importlib\__init__.py", line 126 in import_module
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\pathlib.py", line 533 in import_path
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\python.py", line 608 in _importtestmodule
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\python.py", line 519 in _getobj
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\python.py", line 301 in obj
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\python.py", line 536 in _inject_setup_module_fixture
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\python.py", line 522 in collect
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\runner.py", line 369 in <lambda>
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\runner.py", line 338 in from_call
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\runner.py", line 369 in pytest_make_collect_report
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\runner.py", line 537 in collect_one_node
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\main.py", line 768 in collect
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\runner.py", line 369 in <lambda>
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\runner.py", line 338 in from_call
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\runner.py", line 369 in pytest_make_collect_report
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\runner.py", line 537 in collect_one_node
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\main.py", line 643 in perform_collect
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\main.py", line 332 in pytest_collection
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\main.py", line 321 in _main
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\main.py", line 268 in wrap_session
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\main.py", line 315 in pytest_cmdline_main
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\_pytest\config\__init__.py", line 164 in main
  File "C:\Users\k6789\AppData\Roaming\JetBrains\IntelliJIdea2022.2\plugins\python\helpers\pycharm\_jb_pytest_runner.py", 
  line 51 in <module>
……
C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\xarray\backends\api.py:515: in open_dataset
    engine = plugins.guess_engine(filename_or_obj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

store_spec = None

    def guess_engine(store_spec):
        engines = list_engines()
    
        for engine, backend in engines.items():
            try:
                if backend.guess_can_open(store_spec):
                    return engine
            except Exception:
                warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
……
>       raise ValueError(error_msg)
E       ValueError: did not find a match in any of xarray's currently installed IO backends ['h5netcdf', 'scipy', 'zarr']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
E       https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
E       https://docs.xarray.dev/en/stable/user-guide/io.html

C:\ProgramData\Anaconda3\envs\my1stconda\lib\site-packages\xarray\backends\plugins.py:155: ValueError

```
I have re-installed those io-engines contains `scipy` and so on by conda，but it still crashed and crash report on the 2nd computer became this：
```
ValueError: did not find a match in any of xarray's currently installed IO backends ['scipy', 'zarr']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies……
```
And I appointed `netcdf` engine to read my `.nc` files:
`cur_ds = xa.open_dataset(…… , engine='netcdf4')`
crash report is like this:
```
engine = 'netcdf4'
    def get_backend(engine: str | type[BackendEntrypoint]) -> BackendEntrypoint:
        """Select open_dataset method based on current engine."""
        if isinstance(engine, str):
            engines = list_engines()
            if engine not in engines:
>               raise ValueError(
                    f"unrecognized engine {engine} must be one of: {list(engines)}"
                )
E               ValueError: unrecognized engine netcdf4 must be one of: ['scipy', 'store', 'zarr']
```
So how to solve this? And now I'm sure the crash has not connection with cython.

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>
xarray                    2022.9.0          

conda channel = pypi

</details>

**Comment by max-sixty** [comment] 2022-11-02 17:21
Ref https://github.com/pydata/xarray/discussions/7246

Does `import netCDF4` work? My guess is that the problem is there rather than xarray...

**Comment by max-sixty** [comment] 2022-11-02 18:48
Closing as unrelated to xarray given https://github.com/pydata/xarray/discussions/7246#discussioncomment-4040351

**Closed by max-sixty** 2022-11-02 18:48 UTC
Labels: bug, needs triage
