### ISSUE TITLE
Working with Multidimensional Coordinates - Plotting PlateCarree projection looks strange

### ISSUE THREAD

**Issue by ahuang11** [pydata/xarray#4596] opened 2020-11-19 21:15 UTC
The pixels seem stretched; https://xarray.pydata.org/en/stable/examples/multidimensional-coords.html

**Comment by mathause** [comment] 2020-11-19 23:18
Yes, this is due to an upstream change in matplotlib - see also #4364. mpl tries to infer the edges of the gridcell - which does not work if the data is not monotonic. In the short term we can fix this by passing `shading="flat"`:

```python
ds.Tair[0].plot.pcolormesh(ax=ax, transform=ccrs.PlateCarree(), x='xc', y='yc', add_colorbar=False)
```

however, mpl will eventually remove `shading="flat"`. I am not sure what the best way forward is. mpl recommends to drop a row and column of the data (which it did earlier automatically). See:

https://github.com/SciTools/cartopy/issues/1638#issuecomment-692741908

**Comment by djuncu** [comment] 2020-12-23 16:55
I believe the best (albeit tedious) solution is to resample the coordinates from nx*ny to (nx+1)*(ny+1) before passing the grid to pcolormesh. They should be resampled in such way that the new coordinate positions are on the corner of the quadrilateral as is expected by pcolormesh with flat shading. If only needs to be ensured that none of the 'new' quadliterals crosses the map boundary.

The problem with dropping the last row and column is that it will effectively lead to the position of the values on the map being shifted from their actual position, because pcolormesh assumes that position of value and coordinate different. (May be a minor shift in many cases but still.)

I could not find anything about mpl removing flat shading, are you sure about that?

**Comment by mathause** [comment] 2020-12-23 17:37
> I could not find anything about mpl removing flat shading, are you sure about that?

It's in the deprecation warning: `MatplotlibDeprecationWarning: shading='flat' when X and Y have the same dimensions as C is deprecated since 3.3.  Either specify the corners of the quadrilaterals with X and Y, or pass shading='auto', 'nearest' or 'gouraud', or set rcParams['pcolor.shading'].  This will become an error two minor releases later.`

> I believe the best (albeit tedious) solution is to resample the coordinates from nxny to (nx+1)(ny+1)

We are currently doing this (if the coordinates are monotonic). And mpl also started doing it (and now gives a warning on non-monotonic coordinates). The problem is that with non-monotonic coordinates it leads to wrong results.

> If only needs to be ensured that none of the 'new' quadliterals crosses the map boundary.

I think that's not trivial - see also: SciTools/cartopy#1638 and matplotlib/matplotlib#18317 and has to be fixed upstream. There is a proposed fix, see: SciTools/cartopy#1646.

**Comment by djuncu** [comment] 2020-12-23 19:03
OK I see, thanks for the links.
But the warning says that shading='flat' will be removed as an option only for cases where X/Y dimensions are the same as C; not in general. Sorry, maybe that's just what you meant.

But if the grid is resampled before passing to mpl, flat shading could still be used in the future and non-monotonic coordinates for plotting wouldn't be an issue- well except for the resampling itself.. but they have a good idea for solving that in that cartopy fix. If I understand correctly, their fix 1646 might solve this issue here as well then?

**Comment by mathause** [comment] 2024-02-28 19:09
I think can be closed as fixed upstream

**Closed by mathause** 2024-02-28 19:09 UTC
Labels: topic-plotting
