### ISSUE TITLE
Conversions to Pandas objects fail when mixtures of Index and MultiIndex are present

### ISSUE THREAD

**Issue by carlos-rpg** [pydata/xarray#4765] opened 2021-01-05 10:49 UTC
Hello Xarray team. Thank you very much for your efforts, they have made my job more pleasant.

**What happened**:
When I try to convert a DataArray with a mix of MultiIndex and Index into any pandas object, it returns `NotImplementedError: isna is not defined for MultiIndex`.

**What you expected to happen**:
If the DataArray contains all simple Index objects or one single MultiIndex, the transformation succeeds. I would expect the same from a mixture.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import pandas as pd
import xarray as xr

da = xr.DataArray(
    np.random.randint(0, 10, size=[3, 3, 3]),
    coords={'x': ['x1', 'x2', 'x3'], 'y': ['y1', 'y2', 'y3'], 'z': ['z1', 'z2', 'z3']},
    dims=['x', 'y', 'z']
)

da.to_series() # This works

da.stack(xyz=['x', 'y', 'z']).to_series() # This works

da.stack(xy=['x', 'y']).to_series() # This does not work
```

**Anything else we need to know?**:
It happens the same thing with DataSet.

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None
libhdf5: 1.10.4
libnetcdf: 4.7.3

xarray: 0.16.1
pandas: 1.1.3
numpy: 1.19.1
scipy: 1.5.2
netCDF4: 1.5.3
pydap: installed
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.3.0
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.30.0
distributed: 2.30.1
matplotlib: 3.3.3
cartopy: 0.18.0
seaborn: 0.11.0
numbagg: None
pint: None
setuptools: 50.3.0.post20201006
pip: 20.2.4
conda: 4.9.2
pytest: None
IPython: 7.18.1
sphinx: 3.2.1

</details>

**Comment by keewis** [comment] 2021-01-05 17:29
I think that works as intended, although the error message could definitely be better.

`Series` is limited to 1D arrays, so we have to convert `DataArray` objects with more than one dimension using `stack`. If the object already has a `MultiIndex` this fails because we don't support `da.stack(xy=['x', 'y']).stack(xyz=['xy', 'z'])`.

**Comment by carlos-rpg** [comment] 2021-01-06 09:33
> I think that works as intended, although the error message could definitely be better.
> 
> `Series` is limited to 1D arrays, so we have to convert `DataArray` objects with more than one dimension using `stack`. If the object already has a `MultiIndex` this fails because we don't support `da.stack(xy=['x', 'y']).stack(xyz=['xy', 'z'])`.

It's a pity because having a partial MultiIndex DataArray helps a lot  if there are lots of combinations of `x` and `y` with NA values. My reason to transfort into a pandas object is that I need to `groupby` by 3 dimensions.

**Comment by max-sixty** [comment] 2021-06-26 18:24
I think this does work now?

```python

In [3]:  da.stack(xy=['x', 'y']).to_series()
Out[3]:
z   x   y
z1  x1  y1    2
        y2    5
        y3    6
    x2  y1    0
        y2    7
        y3    1
    x3  y1    4
```

@carlos-rpg you may have also been looking for `to_pandas` or `to_dataframe`.

Closing but please reopen if I'm mistaken!

**Closed by max-sixty** 2021-06-26 18:24 UTC
Labels: topic-error reporting
