### ISSUE TITLE
Better default formatting of timedelta with plot method

### ISSUE THREAD

**Issue by ahuang11** [pydata/xarray#4083] opened 2020-05-19 18:43 UTC
Currently, it shows nanoseconds.
```
import xarray as xr
ds = xr.tutorial.open_dataset('air_temperature')
ds.coords['tau'] = ds['time'] - ds['time'][0]
ds.mean(['lat', 'lon'])['air'].swap_dims({'time': 'tau'}).plot()
```
![image](https://user-images.githubusercontent.com/15331990/82365678-94fed080-99d6-11ea-816f-03a6faa0a4da.png)

**Comment by dcherian** [comment] 2020-05-19 19:39
dupe of #2898. I think this should be fixed by matplotlib though we could copy whatever pandas is doing in the interim.

**Closed by dcherian** 2020-05-19 19:39 UTC
