### ISSUE TITLE
xarray.DataArray > None kills kernel

### ISSUE THREAD

**Issue by rbavery** [pydata/xarray#5049] opened 2021-03-18 04:03 UTC
**What happened**:
```python
import xarray as xr
xr.open_rasterio("test.tif") > None
```
then the kernel dies. This doesn't happen when I create a DataArray from scratch from a python list or numpy array and try the same condition.
Instead I get an appropriate error :

```python
import xarray as xr
import numpy as np
xr.DataArray(np.array([1,2,3, np.nan])) > None
```
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-ee328c447a90> in <module>
      1 import xarray as xr
      2 import numpy as np
----> 3 xr.DataArray(np.array([1,2,3, np.nan])) > None

~/miniconda3/envs/pybayts/lib/python3.7/site-packages/xarray/core/dataarray.py in func(self, other)
   2990             variable = (
   2991                 f(self.variable, other_variable)
-> 2992                 if not reflexive
   2993                 else f(other_variable, self.variable)
   2994             )

~/miniconda3/envs/pybayts/lib/python3.7/site-packages/xarray/core/variable.py in func(self, other)
   2300                 new_data = (
   2301                     f(self_data, other_data)
-> 2302                     if not reflexive
   2303                     else f(other_data, self_data)
   2304                 )

TypeError: '>' not supported between instances of 'float' and 'NoneType'
```
**What you expected to happen**:
An error.

**Minimal Complete Verifiable Example**:

```python
import xarray as xr
xr.open_rasterio("test.tif") > None
```

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-66-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: None
libnetcdf: None

xarray: 0.17.0
pandas: 1.2.3
numpy: 1.20.1
scipy: 1.6.0
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.1
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.3.4
cartopy: None
seaborn: 0.11.1
numbagg: None
pint: None
setuptools: 49.6.0.post20210108
pip: 21.0.1
conda: None
pytest: None
IPython: 7.21.0
sphinx: None
[test.zip](https://github.com/pydata/xarray/files/6161220/test.zip)

</details>

**Comment by max-sixty** [comment] 2021-03-18 04:14
What is `test.tif`?

**Comment by rbavery** [comment] 2021-03-18 04:38
When it is opened it's a DataArray. I saved it out to a .tiff with rioxarray so it has some extra attributes but I'm not sure if those are causing this issue.

**Comment by max-sixty** [comment] 2021-03-18 05:02
Please can you make a reproducible example?

**Comment by rbavery** [comment] 2021-03-18 06:56
I attached the test.tif as a zip file, is that reproducible enough? I don't
know what about the file is causing the issue.

**Comment by keewis** [comment] 2021-03-18 12:46
unfortunately, github doesn't pick up attachments from answer emails, so you will have to upload it using the website.

Could you try whether you have the same issue with this [test file](https://github.com/mapbox/rasterio/raw/master/tests/data/RGB.byte.tif)? That would help us figure out whether that's an environment issue or a bug. Also, could you try using the python / ipython console and see what happens there?

**Comment by rbavery** [comment] 2021-03-18 16:38
Sorry, I thought I attached it to the original issue, here is the test file I'm using:
[test.zip](https://github.com/pydata/xarray/files/6165713/test.zip)

The test file @keewis mentioned does not produce the error.

**Comment by keewis** [comment] 2021-03-18 17:03
you did attach it, but it was hidden in the output of `show_versions`. Anyways, I still can't reproduce the error: running the example with your file in the console (ipython) or jupyterlab always results in the expected error message:
```
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```
could you try it with a fresh environment:
```sh
conda create -n test python=3.9 xarray rasterio notebook
```

**Comment by max-sixty** [comment] 2021-03-25 06:54
Closing, but please reopen with the issue log template if this is still a problem

**Closed by max-sixty** 2021-03-25 06:54 UTC
