### ISSUE TITLE
dask.array as Coordinate variable

### ISSUE THREAD

**Issue by jennakwon06** [pydata/xarray#3852] opened 2020-03-10 05:54 UTC
Hi all,

I was wondering if it was possible to have coordinate variables be also Dask arrays?

I am working with pretty big datasets, where coordinates alone can be too big for memory, so I am wondering how I can achieve working with this.

Thanks!

**Comment by keewis** [comment] 2020-03-29 09:45
sorry for the late reply, @jennakwon06.

At the moment, we rely on `pandas.Index` to provide the indexing functionality, so unfortunately having `dask` arrays as dimension coordinates is not possible. There are plans to eventually support custom indexes (e.g. `dask.dataframe.Index`) but there is still a lot to do (see #1603).

Note that although they are less useful, it is possible to have `dask` arrays in [non-dimension coordinates](https://xarray.pydata.org/en/latest/terminology.html).

**Comment by rabernat** [comment] 2020-05-13 14:18
This is a duplicate of #1094.

**Closed** 2020-05-13 15:00 UTC
Labels: indexing
