### ISSUE TITLE
Combining tiled data sets in xarray

### ISSUE THREAD

**Issue by nicholaskgeorge** [pydata/xarray#4338] opened 2020-08-12 15:12 UTC
I'm working on a project where I need to combine different sets of geographic image tiles into one large tile in Xarray. I am running into an issue. I've made a simplified example bellow.

```python
square1 = xr.DataArray(name="box1", data=np.random.randint(5, size=(3, 2)), coords=[("x", [0,1,2]),('y',[0,1])])
square2 = xr.DataArray(name="box2", data=np.random.randint(5, size=(3, 2)), coords=[("x", [2,3,4]),('y',[0,1])])
square3 = xr.DataArray(name="box3", data=np.random.randint(5, size=(3, 2)), coords=[("x", [0,1,2]),('y',[2,3])])
square4 = xr.DataArray(name="box4", data=np.random.randint(5, size=(3, 2)), coords=[("x", [2,3,4]),('y',[2,3])])

combineddata = xr.combine_by_coords([square1,square2,square3,square4])
```
I thought this is all you need to do it but I get this error

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-57-fc5add80d55a> in <module>
----> 1 xr.combine_by_coords([square1,square2,square3,square4])

~/my-conda-envs/dem/lib/python3.8/site-packages/xarray/core/combine.py in combine_by_coords(datasets, compat, data_vars, coords, fill_value, join, combine_attrs)
    713 
    714     # Group by data vars
--> 715     sorted_datasets = sorted(datasets, key=vars_as_keys)
    716     grouped_by_vars = itertools.groupby(sorted_datasets, key=vars_as_keys)
    717 

~/my-conda-envs/dem/lib/python3.8/site-packages/xarray/core/combine.py in vars_as_keys(ds)
    502 
    503 def vars_as_keys(ds):
--> 504     return tuple(sorted(ds))
    505 
    506 

~/my-conda-envs/dem/lib/python3.8/site-packages/xarray/core/common.py in __bool__(self)
    118 
    119     def __bool__(self: Any) -> bool:
--> 120         return bool(self.values)
    121 
    122     def __float__(self: Any) -> float:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
I am not really sure why this is not working.

**Comment by dcherian** [comment] 2020-08-12 15:55
Thanks for the well written issue @nicholaskgeorge 

This is a duplicate of https://github.com/pydata/xarray/issues/3248 . The solution here is to make all tiles have the same name, use `.to_dataset()` and then pass that to `combine_by_coords`

```
In [9]: square1 = xr.DataArray(name="box", data=np.random.randint(5, size=(3, 2)), coords=[("x", [0,1,2]),('y',[0,1])]) 
   ...: square2 = xr.DataArray(name="box", data=np.random.randint(5, size=(3, 2)), coords=[("x", [2,3,4]),('y',[0,1])]) 
   ...: square3 = xr.DataArray(name="box", data=np.random.randint(5, size=(3, 2)), coords=[("x", [0,1,2]),('y',[2,3])]) 
   ...: square4 = xr.DataArray(name="box", data=np.random.randint(5, size=(3, 2)), coords=[("x", [2,3,4]),('y',[2,3])]) 
   ...:  
   ...: combineddata = xr.combine_by_coords(sq.to_dataset() for sq in [square1,square2,square3,square4])  
```

You can use `combineddata.to_array()` to convert back to a DataArray.

**Comment by nicholaskgeorge** [comment] 2020-08-12 21:49
Thank you @dcherian ! It works. I'm now getting an error telling me the that the axis are not monotonic when I apply it to my real data but I think its something I have to sort out. Sorry I didn't realize this issue was put up before.

**Comment by dcherian** [comment] 2020-08-12 22:50
no worries. I'll close this as a duplicate.

**Closed by dcherian** 2020-08-12 22:50 UTC

**Comment by rsignell-usgs** [comment] 2020-08-13 11:54
@nicholaskgeorge your minimal test would be monotonic if `square2` and `square4` had `x` had coordinates `[3,4,5]` instead of `[2,3,4]`.
