### ISSUE TITLE
Datetime as coordinaets does not convert back to datetime (returns int)

### ISSUE THREAD

**Issue by feefladder** [pydata/xarray#4880] opened 2021-02-07 22:20 UTC
**What happened**:
datetime was in `np.datetime64` formet. When converted t `datetime.datetime` format it returned an `int`
**What you expected to happen**:
`to get a datetime returned
**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
import xarray as xr
import numpy as np
import datetime
date_frame = xr.DataArray(dims='time',coords={'time':pd.date_range('2000-01-01',periods=365)},data=np.zeros(365))
print('pandas date range (datetime): ',pd.date_range('2000-01-01',periods=365)[0])
print('dataframe datetime converted to datetime (int): ',date_frame.coords['time'].data[0].astype(datetime.datetime))
print("normal numpy datetime64 converted to datetime (datetime): ",np.datetime64(datetime.datetime(2000,1,1)).astype(datetime.datetime))
```
output:
```
pandas date range (datetime):  2000-01-01 00:00:00
dataframe datetime converted to datetime (int):  946684800000000000
normal numpy datetime64 converted to datetime (datetime):  2000-01-01 00:00:00
```

if converted to int, it also gives different lengths of int :
date_frame:
946684800000000000
946684800000000
normal datetime64^
**Anything else we need to know?**:

it is also mentioned in [this SO thread](https://stackoverflow.com/a/58174729/14681457) appears to be a problem in the datetime64....

numpy version 1.20.0
pandas version 1.2.1

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 21:08:20) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-59-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: None
libnetcdf: None

xarray: 0.16.2
pandas: 1.2.1
numpy: 1.20.0
scipy: None
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: 2.6.1
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2021.01.1
distributed: 2021.01.1
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
pint: None
setuptools: 49.6.0.post20210108
pip: 21.0.1
conda: None
pytest: None
IPython: 7.20.0
sphinx: None

</details>

**Comment by max-sixty** [comment] 2021-03-25 22:21
Thanks for clear example. As per @keewis 's label, this does look like an upstream issue.

**Comment by keewis** [comment] 2021-03-25 23:05
yes, I believe this to be a `numpy` issue:
```python
date_frame.coords['time'].data[0]
```
returns a `numpy.datetime64[ns]` object, which, casted to `datetime.datetime` using `astype` becomes a `int`. See numpy/numpy#18363 for the upstream issue.

**Comment by Joeperdefloep** [comment] 2021-03-26 08:34
Yes, I created that issue :), should this then be closed?

**Comment by keewis** [comment] 2021-03-26 11:40
Possibly, if this doesn't require any action from us. @spencerkclark, what do you think?

**Comment by spencerkclark** [comment] 2021-03-27 00:26
Yes I think unfortunately there is not much we can do here, since as @keewis noted, `data_frame.coords["time"].data` is a NumPy array.

This issue in general is a little tricky since xarray and pandas use nanosecond-precision datetime values, but `datetime.datetime` objects only have microsecond precision.  See also discussion in https://github.com/numpy/numpy/issues/8546, https://github.com/numpy/numpy/issues/12550, and https://github.com/pydata/xarray/issues/3256.

**Comment by max-sixty** [comment] 2024-04-28 20:13
Closing as dupe of https://github.com/pydata/xarray/issues/3256

**Closed by max-sixty** 2024-04-28 20:13 UTC
Labels: upstream issue
