### ISSUE TITLE
xr.argmin fails with "All-NaN slice encountered".

### ISSUE THREAD

**Issue by SOFIADAL** [pydata/xarray#4481] opened 2020-10-02 17:02 UTC
Hello all!

I tried to find the index of a specific value (minimum value), over a specific dimension of a 4D array:
D=[time,deptht,lat,lon] = [365,32,58,50]

(This variable D contains temperature of a specific region in the ocean) 

In order to find the index of the minimum value in the "deptht" dimension (at each grid point) I did the following:
idx2dT      = D.argmin(dim="deptht",skipna=True) 

(idx2dT[time,lat,lon]. This is a 3D matrix where for each grid point I have a number that represents that index of the minimum value across the "deptht" dimension)

But when I tried the above code: **idx2dT      = D.argmin(dim="deptht",skipna=True)** 
I got the following error:
**ValueError: All-NaN slice encountered.**

I assume this is because there is land-area/coast included in the region of the ocean I picked, which means that all the temperature values at "deptht" dimension over the land-grid points are NaN. So the xr.argmin does not work for some reason.

When I tried : idx2dT      = D.argmin(dim="deptht",skipna=False), it sees as the minimum value of my "deptht" the NaN value, so I get back a plot which is wrong.

Any ideas on how to fix this?

Thanks,
Sofi

**Comment by dcherian** [comment] 2020-10-02 17:48
> this is because there is land-area/coast included in the region of the ocean I picked, which means that all the temperature values at "deptht" dimension over the land-grid points are NaN.

Your diagnosis is right. I would `fill` in a obviously wrong value at NaN points, then calculate `argmin` and mask out the result.

**Comment by SOFIADAL** [comment] 2020-10-02 17:55
Ok Deepak,

Thanks a lot for this answer.I will do that! Thanks for the help!

 One last question I had. In order not to avoid (if possible) touching the NaNs, is there a way with xarray isel or sel or loc to actually _select___ **a specific value** (not its index or its label) and give back its index on a matrix (in the case of the min/max we have argmin/argmax, but in any other case how do we do it?I assume with where function right?)

Sofi

**Comment by dcherian** [comment] 2020-10-02 18:59
Yes that sounds like a `where` combined with `argmin` or maybe `numpy.nonzero` ?

**Comment by mathause** [comment] 2020-10-03 06:39
Would be nice if there was a switch to allow all nan slices (maybe return nan?).

`idxmin` supoorts a `fill_value` - you could also test this.

**Comment by SOFIADAL** [comment] 2020-10-03 12:20
Thank you a lot for these suggestions.
Yes I though of idxmin. Thank you!


Sofi

**Comment by dcherian** [comment] 2020-10-03 14:18
> Would be nice if there was a switch to allow all nan slices (maybe return nan?).

See https://github.com/pydata/xarray/issues/3884. We can't return nan because `argmax` and `argmin` return int. We should add `fill_value` to fix this.

**Comment by mathause** [comment] 2020-10-05 07:48
Yes, is may be possible to use the code of idxmin for argmin, setting `fill_value=None` (= raise) as default.

**Comment by max-sixty** [comment] 2024-09-25 23:25
I think a dupe of #3884 ?

**Closed** 2024-09-26 00:14 UTC
Labels: plan to close
