### ISSUE TITLE
Polyfit performance on large datasets - Suboptimal dask task graph

### ISSUE THREAD

**Issue by jbusecke** [pydata/xarray#5629] opened 2021-07-22 17:19 UTC
**What happened**:

I am trying to calculate a linear trend over a large climate model simulation. I use rechunker to chunk the data along the horizontal dimensions and make sure that the time dimension (along which I want to calculate the fit) is not chunked. 
In my realistic example, this blows up the memory of my workers. 

**What you expected to happen**:
I expected this to work very smoothly because it should be embarassingly parallel (no information of sourrounding chunks is needed and the time dimension is complete in each chunk).

**Minimal Complete Verifiable Example**:
I think this minimal example shows that the task graph created is not ideal

```python
import xarray as xr
import dask.array as dsa
da = xr.DataArray(dsa.random.random((4,6, 100), chunks=(1,2,100)), dims=['x','y', 'time'])
da
```

<img width="624" alt="image" src="https://user-images.githubusercontent.com/14314623/126680660-3fc15f80-63a8-42e0-96ee-c1c8ff9b90d3.png">

> Note that the original data array has 12 chunks

When I apply polyfit I get this
```python
poly = da.polyfit('time', 1)
poly
```

<img width="615" alt="image" src="https://user-images.githubusercontent.com/14314623/126680784-67ed42c7-f2d8-4f1b-b875-26e363c95530.png">

Now the number of chunks has decreased to 4? I am not sure why, but this indicates to me that my problem might be related to #4554.

When I look at the task graph it seems that this explains why for very large dataset the computation blows up:
![image](https://user-images.githubusercontent.com/14314623/126680985-20ca0fdc-35fb-44fd-aa33-a27b4732ef4c.png)

As I said before I would expect this calculation to be fully parallelizable, but there seems to be some aggregation/rechunking steps in the bottom layer. How 'bad' these get (e.g. how many input chunks get lumped together in the `rechunk/merge` step, depends on the chunking structure of the horizontal axes. 

cc @TomNicholas

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.89+
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.17.0
pandas: 1.2.4
numpy: 1.20.2
scipy: 1.6.2
netCDF4: 1.5.6
pydap: installed
h5netcdf: 0.11.0
h5py: 3.2.1
Nio: None
zarr: 2.7.1
cftime: 1.4.1
nc_time_axis: 1.2.0
PseudoNetCDF: None
rasterio: 1.2.2
cfgrib: 0.9.9.0
iris: None
bottleneck: 1.3.2
dask: 2021.04.1
distributed: 2021.04.1
matplotlib: 3.4.1
cartopy: 0.19.0
seaborn: None
numbagg: None
pint: 0.17
setuptools: 49.6.0.post20210108
pip: 20.3.4
conda: None
pytest: None
IPython: 7.22.0
sphinx: None

</details>

**Comment by dcherian** [comment] 2021-07-22 17:27
It's the same thing: `stack` is a reshape which can be very inefficient with dask. I think we want to replace the stack+apply_along_axis approach with `xr.apply_ufunc(np.polyfit, ..., vectorize=True)`.

**Comment by jbusecke** [comment] 2021-07-22 17:28
Should I close this one then?

**Comment by TomNicholas** [comment] 2021-07-22 17:31
Thanks for the clear example @jbusecke . I think you example is helpful enough that we should keep this open (even if the same PR will hopefully close both this and #4554)

Was about to say the same @dcherian! @aulemahal what do you think about how easy it might be to change `polyfit` to use `apply_ufunc`?

**Comment by slevang** [comment] 2021-07-22 20:37
Potentially a useful comparison: here is the task graph for the same problem posed to `da.curvefit`, which uses `xr.apply_ufunc(scipy.optimize.curvefit, ..., vectorize=True)`. Looks a lot cleaner, and I think `xr.polyfit` could be re-implemented this way without much trouble.
```python
import xarray as xr
import dask.array as dsa

def linear(x, m, b):
    return m * x + b

da = xr.DataArray(dsa.random.random((4,6, 100), chunks=(1,2,100)), dims=['x','y', 'time'])
fit = da.curvefit('time', linear).curvefit_coefficients
```
![image](https://user-images.githubusercontent.com/39069044/126705616-4fa914a7-14f0-4727-bf3a-e916627de4e7.png)

**Comment by aulemahal** [comment] 2021-07-26 17:52
>  @aulemahal what do you think about how easy it might be to change polyfit to use apply_ufunc?

Should be easy! The code was written without apply_ufunc for a few reasons, one being that using `apply_ufunc+vectorize` was slower than the `apply_along_axis` trick it currently uses. But, with the issue raised here, that might not be true...

**Comment by dcherian** [comment] 2021-07-26 17:55
You could write a wrapper that does `reshape` + `apply_along_axis` and call that wrapper in `apply_ufunc` without `vectorize`

**Comment by kmuehlbauer** [comment] 2021-07-27 04:54
`apply_ufunc` was refactored to use `dask.array.apply_gufunc` (which moves the vectorization to dask) after implementation of `polyfit`.
So those concerns about slowness of `apply_ufunc` + vectorization where based on the formerly used `_apply_blockwise` approach and might not be an issue any more with the current implementation of `apply_ufunc `.

**Comment by dcherian** [comment] 2021-11-03 21:39
In reading through #5933, I realized there's an alternate solution that preserves the desirable feature of fitting along chunked dimensions (at least for skipna=False)

Since we are only ever fitting along one dimension, we can apply the reshape operation blockwise. As long as we reshape back in a consistent manner (again blockwise) this is identical to our current stacking approach, but substantially more efficient

``` python
from dask.array.utils import assert_eq


def reshape_block(arr, output_chunks):
    """
    Blockwise reshape array to match output_chunks

    This method applies a reshape operation blockwise, so it only makes sense if
    you do not care about the order of elements (along reshaped axes) after reshaping.
    The order of elements will depend on the chunking of ``arr``.
    It is substantially more efficient than a usual reshape, which makes sure array elements
    appear in a numpy-like order regardless of chunking.
    
    Based on https://github.com/dask/dask/issues/4855#issuecomment-497062002
    """
    name = "reshape-block-" + tokenize(arr)
    ichunks = tuple(range(len(chunks_v)) for chunks_v in arr.chunks)
    ochunks = tuple(range(len(chunks_v)) for chunks_v in output_chunks)

    dsk = {
        (name, *ochunk): (np.reshape, (arr.name, *ichunk), oshape)
        for ichunk, ochunk, oshape in zip(
            product(*ichunks), product(*ochunks), product(*output_chunks)
        )
    }

    graph = HighLevelGraph.from_collections(name, dsk, dependencies=[arr])
    res = Array(graph, name, output_chunks, arr.dtype, meta=arr._meta)

    return res

# assumes we're collapsing axes (0,1) and preserving axis 2
output_chunks = (tuple(map(np.product, product(*arr.chunks[:2]))),) + (arr.chunks[-1],)
reshaped = reshape_block(arr, output_chunks)

# make sure that we roundtrip
actual = reshape_block(reshaped, arr.chunks)
assert_eq(actual, arr) # True
```
``` python
def new_polyfit(da):
    arr = da.data
    output_chunks = (tuple(map(np.product, product(*arr.chunks[:2]))),) + (
        arr.chunks[-1],
    )
    reshaped = xr.DataArray(reshape_block(arr, output_chunks), dims=("xy", "time"))
    fit = reshaped.polyfit("time", 1, skipna=True)
    result = xr.Dataset()
    for var in fit:
        result[var] = (
            ("degree", "x", "y"),
            reshape_block(fit[var].data, ((2,),) + arr.chunks[:-1]),
        )

    result["x"] = da["x"]
    result["y"] = da["y"]
    result["degree"] = fit["degree"]
    return result


poly = da.polyfit("time", 1, skipna=False)

xr.testing.assert_allclose(poly, new_polyfit(da))  # True!
```

Here's the graph 1 chunk along time (like @jbusecke's example, and skipna=True)
![image](https://user-images.githubusercontent.com/2448579/140196626-c6316d0a-468c-4540-822a-c53156c7040b.png)

And when the time dimension is chunked (and skipna=False)

![image](https://user-images.githubusercontent.com/2448579/140196389-0e06c04f-1f70-408f-89c6-3d7d8064c9c7.png)

**Comment by Illviljan** [comment] 2021-11-04 02:58
@dcherian Is that something that could be implemented in apply_ufunc? Not being able to apply along a chunked dim I think happens quite often, right?

**Comment by dcherian** [comment] 2021-11-04 15:27
The problem is that there is no general solution here. You have to write a chunk-aware function and then use `apply_ufunc(..., dask="allowed")`. This suggestion only works because dask's `lstsq` can work with chunked dimensions.

**Comment by dcherian** [comment] 2021-11-04 16:51
>  Is that something that could be implemented in apply_ufunc?

**Comment by Illviljan** [comment] 2021-11-04 19:22
I was thinking the general idea of reshape_block seems like a clever trick to get around the apply_ufunc constraints for some other functions as well. But maybe there aren't that many functions that could make use of it.

**Comment by TomNicholas** [comment] 2021-11-04 19:25
> I was thinking the general idea of reshape_block seems like a clever trick to get around the apply_ufunc constraints and could be used for some other functions as well. But maybe there aren't that many functions that could make use of it.

The idea seems similar to [what we used in xhistogram](https://github.com/xgcm/xhistogram/pull/49), which uses blockwise to apply a function that reshapes the data in that block to be 1D.

**Comment by dcherian** [comment] 2021-11-04 19:56
>  a clever trick to get around the apply_ufunc constraints

To clarify, the constraint here is that `lstsq` expects 2D arrays, that's why the reshaping was needed in the first place.

`apply_ufunc(..., dask="parallelized")` automatically applies your function blockwise which only makes sense if there is a single chunk along the core dimension, hence that constraint.

`apply_ufunc(..., dask="allowed")` has no constraints, your function has to know how to deal with chunked data though.

> uses blockwise to apply a function that reshapes the data in that block to be 1D.

Yes, same idea. Though when you do it that way, you have to implement the function you're applying (that xhistogram PR reimplements `dask.array.bincount`). Reimplementing `lstsq` is a lot more complicated, hence this approach.

**Comment by phofl** [comment] 2024-08-14 13:54
The explosion in chunk sizes will be fixed in the next dask release, task graph is still relatively complex though

**Comment by phofl** [comment] 2024-08-19 13:26
Looking at this again, I was incorrect. Here is the graph of the current implementation:

![polyfit](https://github.com/user-attachments/assets/5bb53680-826c-4d2c-8fc3-624e6bc47cf8)

This is basically embarrassingly parallel, so I think we can close this one?

**Comment by dcherian** [comment] 2024-08-19 15:41
Very nice! yeah I think @jbusecke's example is the case where the "blockwise reshaping" isn't really needed because the outer most axis has chunk size 1. 

let's leave it open for the more general solution.

**Closed** 2024-11-13 16:20 UTC
Labels: topic-performance
