### ISSUE TITLE
xr.concat loses coordinate dtype information with recarrays in 0.9

### ISSUE THREAD

**Issue by mivade** [pydata/xarray#1434] opened 2017-05-30 19:04 UTC
Simple example script:

```python
import numpy as np
import xarray as xr

p1 = np.array([('A', 180), ('B', 150), ('C', 200)], dtype=[('name', '|S256'), ('height', int)])
p2 = np.array([('D', 170), ('E', 250), ('F', 150)], dtype=[('name', '|S256'), ('height', int)])

data1 = np.arange(50, 80, 1, dtype=np.float)
data2 = data1 * 2

dims = ['measurement', 'participant']

da1 = xr.DataArray(
    data1.reshape(10, 3),
    coords={
        'measurement': np.arange(10),
        'participant': p1,
        'samplerate': 1
    },
    dims=dims
)

da2 = xr.DataArray(
    data2.reshape(10, 3),
    coords={
        'measurement': np.arange(10),
        'participant': p2,
        'samplerate': 1
    },
    dims=dims
)

combined = xr.concat([da1, da2], dim='participant')
print(da1.participant.dtype)
print(da2.participant.dtype)
print(combined.participant.dtype)
```

With `xarray` version 0.9.5 (and 0.8.2), this results in:

```
[('name', 'S256'), ('height', '<i8')]
[('name', 'S256'), ('height', '<i8')]
object
```

We have to go all the way back to xarray version 0.7 to get the expected behavior:

```
[('name', 'S256'), ('height', '<i8')]
[('name', 'S256'), ('height', '<i8')]
[('name', 'S256'), ('height', '<i8')]
```

**Comment by shoyer** [comment] 2017-05-30 23:08
Thanks for the report, I'm marking this as a bug.

The issue is with [these lines](https://github.com/pydata/xarray/blob/master/xarray/core/variable.py#L1232-L1242
) in `IndexVariable.concat`. We defer to pandas for concatenating coordinate labels, but pandas doesn't handle structured dtypes properly (it converts them to `dtype=object`). This is part of why we have [`PandasIndexAdapter`](https://github.com/pydata/xarray/blob/8df660b37692e42965a672563941d85ed6d55229/xarray/core/indexing.py#L494).

It seems like we now need some more complex logic for toggling between pandas `Index.append()` and `numpy.concatenate`, based on the Index dtypes.

**Comment by mivade** [comment] 2017-05-30 23:13
Thanks for the pointer. I had looked at the code to try to understand what was happening but wasn't quite sure.

Is there an advantage to using pandas for concatenation over `numpy.concatenate`?

**Comment by shoyer** [comment] 2017-05-30 23:20
> Is there an advantage to using pandas for concatenation over numpy.concatenate?

Yes, otherwise we loose pandas (d)type information. For example, a `MultiIndex` gets turned into a `dtype=object` array of tuples.

**Comment by ctw** [comment] 2018-05-03 20:36
I noticed that this is still an issue in v0.10.3. I looked through the discussion in the (closed) pull request https://github.com/pydata/xarray/pull/1438 , but it's not obvious to me what (else) is required to fix this. Are there any plans to fix this bug or can somebody point me in the right direction so I can try to help fix it?

**Comment by ctw** [comment] 2018-05-12 16:41
@shoyer might you have any insights on this?

**Comment by shoyer** [comment] 2018-05-13 22:27
@ctw I'm not sure why #1438 was closed (I think that was by mistake), but we would still need a fix along those lines to fix this issue.

**Comment by aldanor** [comment] 2019-03-20 00:34
Looks like this is still a problem, just tested on 0.11.3 and it still results in `object`...

**Comment by kmuehlbauer** [comment] 2023-01-23 07:05
Works for me in latest main. #1438 might be closed, too.

**Comment by keewis** [comment] 2023-01-23 10:23
Works for me, as well, so I'm closing this.

**Closed by keewis** 2023-01-23 10:23 UTC
Labels: bug, topic-combine
