### ISSUE TITLE
AssertionError when storing datetime coordinates of wrong units

### ISSUE THREAD

**Issue by gerritholl** [pydata/xarray#1494] opened 2017-07-27 16:11 UTC
The following code should probably fail somewhere else than with an `AssertionError` triggered by `to_netcdf`:

```
$ cat mwe.py
#!/usr/bin/env python3.6

import numpy
import xarray

x = xarray.DataArray(
    [1, 2, 3],
    dims=["X"],
    coords={"X": numpy.zeros(shape=3, dtype="M8[ms]")})

x.to_netcdf("/tmp/test.nc")
$ python3.6 mwe.py
Traceback (most recent call last):
  File "mwe.py", line 11, in <module>
    x.to_netcdf("/tmp/test.nc")
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/core/dataarray.py", line 1351, in to_netcdf
    dataset.to_netcdf(*args, **kwargs)
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/core/dataset.py", line 977, in to_netcdf
    unlimited_dims=unlimited_dims)
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/backends/api.py", line 573, in to_netcdf
    unlimited_dims=unlimited_dims)
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/core/dataset.py", line 916, in dump_to_store
    unlimited_dims=unlimited_dims)
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/backends/common.py", line 244, in store
    cf_variables, cf_attrs = cf_encoder(variables, attributes)
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/conventions.py", line 1089, in cf_encoder
    for k, v in iteritems(variables))
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/conventions.py", line 1089, in <genexpr>
    for k, v in iteritems(variables))
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/conventions.py", line 734, in encode_cf_variable
    var = maybe_encode_datetime(var)
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/conventions.py", line 585, in maybe_encode_datetime
    data, encoding.pop('units', None), encoding.pop('calendar', None))
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/xarray/conventions.py", line 293, in encode_cf_datetime
    assert dates.dtype == 'datetime64[ns]'
AssertionError
```

**Comment by shoyer** [comment] 2019-06-30 04:28
I tried this with xarray 0.12.2, and I could not reproduce the issue. It seems to have been fixed inadvertently...

**Closed by shoyer** 2019-06-30 04:28 UTC
Labels: bug
