### ISSUE TITLE
DOC: combining datasets with different coordinates

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1495] opened 2017-07-28 15:45 UTC
It would be nice to have documentation recipe showing how to combine datasets with different latitude/longitude arrays, as often occurs due to numerical precision issues. It's a little more complicated than just using `xarray.open_mfdataset()`, and comes up with some regularity.

**Comment by rabernat** [comment] 2019-07-12 19:20
This is essentially a duplicate of #1391. I am going to close this in favor of that.

**Closed by rabernat** 2019-07-12 19:20 UTC
Labels: documentation, good first issue, help wanted
