### ISSUE TITLE
Is it possible to append_dim to netcdf stores

### ISSUE THREAD

**Issue by hmaarrfk** [pydata/xarray#4394] opened 2020-08-31 18:02 UTC
**Is your feature request related to a problem? Please describe.**
Feature request: It seems that it should be possible to append to netcdf4 stores along the unlimited dimensions. Is there an example of this?

**Describe the solution you'd like**
I would like the following code to be valid:
```python
from xarray.tests.test_dataset import create_append_test_data
ds, ds_to_append, ds_with_new_var = create_append_test_data()

filename = 'test_dataset.nc'
# Choose any one of
# engine : {'netcdf4', 'scipy', 'h5netcdf'}
engine = 'netcdf4'
ds.to_netcdf(filename, mode='w', unlimited_dims=['time'], engine=engine)
ds_to_append.to_netcdf(filename, mode='a', unlimited_dims=['time'], engine=engine)
```

**Describe alternatives you've considered**
I guess you could use zarr, but the fact that it creates multiple files is a problem.

**Additional context**
xarray version: 0.16.0

**Comment by dopplershift** [comment] 2020-08-31 22:08
Duplicate of #1672?

**Comment by dcherian** [comment] 2020-08-31 22:11
Thanks! Closing as duplicate of #1672

**Closed by dcherian** 2020-08-31 22:11 UTC
Labels: backends
