### ISSUE TITLE
Use weighted with coarsen?

### ISSUE THREAD

**Issue by ahuang11** [pydata/xarray#4210] opened 2020-07-08 19:53 UTC
I want to do something similar as xesmf's weighted regridding, but without the need to install esmpy which has a lot of dependencies.

Are variations of the following possible?
```
ds.weighted(coslat_weights).coarsen(lat=2, lon=2).mean()
```

```
ds.coarsen(lat=2, lon=2).weighted(coslat_weights).mean()
```

**Comment by dcherian** [comment] 2020-07-08 20:01
I'm closing this as duplicate of #3937 so all the discussion is in one place.

@ahuang11 I'll copy your post there.

**Closed by dcherian** 2020-07-08 20:01 UTC
