### ISSUE TITLE
Contourplot not producing plot when data below colorbar level and extend='neither'

### ISSUE THREAD

**Issue by jorgsk** [pydata/xarray#1578] opened 2017-09-19 08:23 UTC
I'm plotting several datasets on a map with contourf with the same colorbar levels where some datasets have no data above the lowest level. I expect these plots to simply be blank. The default behavior is instead that 'extend' becomes set to 'min' behind the scenes, changing the colorabar relative to the other plots. When I set extend to 'neither' explicitly, I get an error from matplotlib: "ValueError: 'bboxes' cannot be empty". The plot call looks like this:

`data.plot.contourf(ax=ax, transform=ccrs.PlateCarree(),                                                               vmin=levels[0], vmax=levels[-1], levels=levels,                                                                cmap=plt.get_cmap('viridis_r'), extend='neither', extent=(-17, 25, 52, 73)`

I found that if I revert this bug-fixe from Cartopy: https://github.com/SciTools/cartopy/issues/811 I get the expected behavior.

Not sure if this issue should go to Cartopy but I'm starting here.

Matplotlib version  2.0.0
Xarray version  0.9.6
Cartopy version  0.15.1

**Comment by fmaussion** [comment] 2017-09-19 08:55
Could you provide a minimal example demonstrating the problem, without 
using cartopy and with dummy data? This will help us to reproduce the 
problem locally.

**Comment by Plantain** [comment] 2018-09-09 09:54
This happens with extend='max' too.

**Comment by dcherian** [comment] 2018-09-09 11:29
@Plantain can you provide a reproducible example please?

**Comment by Plantain** [comment] 2018-10-30 18:19
There is a reproducible example here: https://github.com/SciTools/cartopy/issues/811

**Comment by karlwx** [comment] 2019-03-27 13:31
I experienced the same issue when using contourf. It was fixed by setting extend='both' in the contourf function, and I got rid of the triangles in my colorbar by setting extendfrac=0 in the colorbar function.

The funny thing is, the code worked just fine yesterday, but when I ran it again today, I encountered this problem. 

Non-working code:
`pcp = ax.contourf(x, y, data, cmap=cmap, levels=bounds, transform=proj, norm=norm)
cb = plt.colorbar(pcp, cmap=cmap, pad=0.01, shrink=1, norm=norm, ticks=labels, orientation='horizontal')`

Working code:
`pcp = ax.contourf(x, y, data, cmap=cmap, levels=bounds, transform=proj, norm=norm, extend='both')
cb = plt.colorbar(pcp, cmap=cmap, pad=0.01, shrink=1, norm=norm, ticks=labels, orientation='horizontal', extendfrac=0)`

I'm pulling data from the NCEP NOMADS server, not sure if that matters, but I've found the data download to be slow and pretty questionable at times.

**Comment by karlwx** [comment] 2019-03-27 13:37
Also worth mentioning that I had the same issue with pcolormesh, but only when I used the option shading='gouraud'. 
The map ended up plotting as expected, but still returned the Value Error, so I ignored the error with try and except and continued. 
Is there really not a fix for any of this yet?

**Comment by dcherian** [comment] 2019-03-27 14:40
This looks like a matplotlib/cartopy problem since you aren't going through the xarray.plot interface :)

**Comment by gPapav** [comment] 2019-03-29 22:44
I have exactly the same problem with GFS data @karlwx but it seems like a python-related issue! 
The script was working perfect until last week and now it crashes.

**Comment by kmuehlbauer** [comment] 2024-10-31 13:24
If this is still an issue, please reopen with MCVE or open a completely new issue.

**Closed by kmuehlbauer** 2024-10-31 13:24 UTC
Labels: topic-plotting
