### ISSUE TITLE
Why must lat=slice() arguments be decreasing?

### ISSUE THREAD

**Issue by brianmapes** [pydata/xarray#6327] opened 2022-03-03 17:00 UTC
### What is your issue?

Many meteorological grids seem to have latitude decreasing. I am constantly forgetting this, and getting garbled results when I use slice(lat1,lat2).  I can't think of any use case for which this slice ordering needs to be such a pitfall. Couldn't slice.py be set up to return the indicated interval, no matter which order the arguments are passed? 

Would any user have any meaningful analysis fail if this convenience were programmed in to slice.py? 

"Indexing axes with monotonic decreasing labels also works, as long as the slice or .loc arguments are also decreasing"

(Forgive a first-timer if this is the wrong place/format for this question. I searched past issues for slice and order and found no existing issue.)

**Comment by keewis** [comment] 2022-03-03 17:16
see #1613 for a pretty thorough discussion. Very short summary: we inherit this behavior from `pandas`

**Comment by dcherian** [comment] 2022-03-03 17:18
@brianmapes  could you comment on that thread regarding your opinion of a new `xr.Between` object that would explicitly ignore underlying coordinate order.

In the mean time I'm closing this issue as a duplicate of #1613

**Closed by dcherian** 2022-03-03 17:18 UTC
Labels: needs triage
