### ISSUE TITLE
Attribute of coodinate removed on input dataArray when used in xr.apply_ufunc

### ISSUE THREAD

**Issue by lanougue** [pydata/xarray#9114] opened 2024-06-13 13:39 UTC
### What happened?

Using DataArray 'a' as input of apply_ufunc remove attribute of coordinate of 'a'

### What did you expect to happen?

Input DataArray 'a' should stay unchanged when passed to the function.

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import numpy as np
a = xr.DataArray(np.random.rand(2,3), dims=('x','y'), coords={'x':np.arange(2), 'y':np.arange(3)})
a.x.attrs.update({'s':0.1})
res = xr.apply_ufunc(np.multiply, a, a,input_core_dims=[['x','y'],['x','y']], output_core_dims=[['x','y']])
print(a['x'].attrs)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]
python-bits: 64
OS: Linux
OS-release: 3.12.53-60.30-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.9.3-development

xarray: 2024.5.0
pandas: 2.2.2
numpy: 1.26.4
scipy: 1.13.1
netCDF4: 1.6.5
pydap: None
h5netcdf: None
h5py: None
zarr: None
cftime: 1.6.3
nc_time_axis: None
iris: None
bottleneck: None
dask: 2024.5.1
distributed: 2024.5.1
matplotlib: 3.8.4
cartopy: 0.23.0
seaborn: None
numbagg: None
fsspec: 2024.5.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 70.0.0
pip: 24.0
conda: None
pytest: None
mypy: None
IPython: 8.20.0
sphinx: None

</details>

**Comment by keewis** [comment] 2024-06-13 14:24
this very much looks like a duplicate of #8047. Can you confirm?

**Comment by lanougue** [comment] 2024-06-13 14:48
Yes, but not restricted to  `keep_attrs=False` (as stated in the title of the issue)

**Comment by keewis** [comment] 2024-06-13 14:52
`keep_attrs=False` is the default if you don't pass it explicitly. I can confirm that `xr.apply_ufunc(..., keep_attrs=True)` retains the attributes.

Given that, I'll close this as a duplicate. Feel free to follow up on this in #8047.

**Closed by keewis** 2024-06-13 14:52 UTC
Labels: bug
