### ISSUE TITLE
Inconsistent time parsing when using open_dataset linux vs mac

### ISSUE THREAD

**Issue by stackjohn** [pydata/xarray#8468] opened 2023-11-18 20:17 UTC
### What is your issue?

Is there a reason why the following code would produce datasets which have differently parsed timestamps?

```python
url = (
    "https://nomads.ncep.noaa.gov/dods/gfs_0p25_1hr/gfs"
    + mdate
    + "/gfs_0p25_1hr_"
    + get_init_hr(hour)
    + "z"
)
ds = xr.open_dataset(url)
print(ds["time"])
```

On a mac arm based machine I see the following:

```
<xarray.DataArray 'time' (time: 121)>
array(['2023-11-18T12:00:00.000000000', '2023-11-18T13:00:00.000000000',
       '2023-11-18T14:00:00.000000000', '2023-11-18T15:00:00.000000000',
       '2023-11-18T16:00:00.000000000', '2023-11-18T17:00:00.000000000',
       '2023-11-18T18:00:00.000000000', '2023-11-18T19:00:00.000000000',
```
etc

On Linux amd machine I see the following:

```
<xarray.DataArray 'time' (time: 121)>
array(['2023-11-18T12:00:00.000000000', '2023-11-18T12:59:59.999997000',
       '2023-11-18T14:00:00.000003000', '2023-11-18T15:00:00.000000000',
       '2023-11-18T15:59:59.999997000', '2023-11-18T17:00:00.000003000',
       '2023-11-18T18:00:00.000000000', '2023-11-18T18:59:59.999997000',
```
etc

Is this expected? It meant rewriting time slice logic code which seemed to be failing (not a big issue) but it also seems to be causing issues on the linux machine when trying to query the data back from the server on the linux machine. All works fine on the mac. 

<details>
<summary>Mac xarray versions</summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.6 (main, Nov  2 2023, 04:39:43) [Clang 14.0.3 (clang-1403.0.22.14.1)]
python-bits: 64
OS: Darwin
OS-release: 22.4.0
machine: arm64
processor: arm
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: ('en_GB', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.9.3-development

xarray: 2023.11.0
pandas: 2.1.3
numpy: 1.26.2
scipy: 1.11.3
netCDF4: 1.6.5
pydap: None
h5netcdf: 1.3.0
h5py: 3.10.0
Nio: None
zarr: 2.16.1
cftime: 1.6.3
nc_time_axis: 1.4.1
iris: None
bottleneck: 1.3.7
dask: 2023.11.0
distributed: 2023.11.0
matplotlib: 3.8.2
cartopy: 0.22.0
seaborn: 0.13.0
numbagg: 0.6.2
fsspec: 2023.10.0
cupy: None
pint: 0.22
sparse: None
flox: 0.8.2
numpy_groupies: 0.10.2
setuptools: 68.2.2
pip: 23.2.1
conda: None
pytest: None
mypy: None
IPython: 8.17.2
sphinx: None
</details>

<details>
<summary>Linux xarray versions</summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.6 (main, Nov 18 2023, 17:37:05) [GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.15.0-87-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: ('en_GB', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.9.3-development

xarray: 2023.11.0
pandas: 2.1.3
numpy: 1.26.2
scipy: 1.11.3
netCDF4: 1.6.5
pydap: None
h5netcdf: 1.3.0
h5py: 3.10.0
Nio: None
zarr: 2.16.1
cftime: 1.6.3
nc_time_axis: 1.4.1
iris: None
bottleneck: 1.3.7
dask: 2023.11.0
distributed: 2023.11.0
matplotlib: 3.8.2
cartopy: 0.22.0
seaborn: 0.13.0
numbagg: 0.6.2
fsspec: 2023.10.0
cupy: None
pint: 0.22
sparse: None
flox: 0.8.2
numpy_groupies: 0.10.2
setuptools: 68.2.2
pip: 23.1.2
conda: None
pytest: None
mypy: None
IPython: 8.17.2
sphinx: None
</details>

I've tried opening the dataset with various combinations such as `decode_times:false` and `use_cftime` on the linux side of things but it doesn't seem to make a difference. Is there a flag I can pass to `open_dataset` on the linux side of things so it behaves in the same way?

**Comment by max-sixty** [comment] 2023-11-18 21:40
We'd really need a reproducible example here. Could you fill out the bug report template with an MCVE?

If that's not worthwhile, and anyone knows off-hand, feel free to comment here.

**Comment by stackjohn** [comment] 2023-11-18 21:52
@max-sixty My apologies for the oversight. 

Here is a complete example to reproduce the output of the print statements:

```python
from datetime import datetime
import xarray as xr


startTime = datetime.now()

m_date = "20200903"
m_hour = "12"

year = startTime.year

if startTime.month < 10:
    month = "0" + str(startTime.month)
else:
    month = str(startTime.month)

if startTime.day < 10:
    day = "0" + str(startTime.day)
else:
    day = str(startTime.day)

if startTime.hour < 10:
    hour = "0" + str(startTime.hour)
else:
    hour = str(startTime.hour)

mdate = str(year) + str(month) + str(day)


def get_init_hr(hour):
    if int(hour) < 6:
        init_hour = "00"
    elif int(hour) < 11:
        init_hour = "00"
    elif int(hour) < 17:
        init_hour = "06"
    elif int(hour) < 22:
        init_hour = "12"
    else:
        init_hour = "00"
    return init_hour



url = (
    "https://nomads.ncep.noaa.gov/dods/gfs_0p25_1hr/gfs"
    + mdate
    + "/gfs_0p25_1hr_"
    + get_init_hr(hour)
    + "z"
)


ds = xr.open_dataset(url)
print(ds['time'])
```

Can this be reopened or should I resubmit?

**Comment by max-sixty** [comment] 2023-11-18 22:01
Thanks!

I get an error `RuntimeError: Failed to decode variable 'time': NetCDF: Malformed or inaccessible DAP2 DATADDS or DAP4 DAP response` but possibly that's because I don't have some dependencies installed (I don't use this decoding much myself).

Can we edit the example so it's verifiable? Does it need the current time? Can it just be a URL?

**Comment by stackjohn** [comment] 2023-11-18 22:10
@max-sixty I often get the same error. If you retry it may work. I'm honestly not sure why it fails like that, it's very intermittent. If you retry it may work. 

As far as know the time must be passed in to resolve a date. The data is not kept indefinitely and so if someone comes to run this in a month or so they will need to programatically generate a date.

**Comment by max-sixty** [comment] 2023-11-18 22:24
OK. It's not a perfect example — instead we could grab a file, isolating the parts that are causing the issues, and publish that. But let's see if anyone has ideas, we can leave this open for a bit

**Comment by spencerkclark** [comment] 2023-11-18 22:40
I think this is because the times are encoded with floats, so one may not get the identical result upon decoding on different systems:
```
>>> url = "https://nomads.ncep.noaa.gov/dods/gfs_0p25_1hr/gfs20231116/gfs_0p25_1hr_06z"
>>> ds = xr.open_dataset(url, decode_times=False)
>>> ds.head(time=10).time
<xarray.DataArray 'time' (time: 10)>
array([738841.25    , 738841.291667, 738841.333333, 738841.375   ,
       738841.416667, 738841.458333, 738841.5     , 738841.541667,
       738841.583333, 738841.625   ])
Coordinates:
  * time     (time) float64 7.388e+05 7.388e+05 ... 7.388e+05 7.388e+05
Attributes:
    grads_dim:      t
    grads_mapping:  linear
    grads_size:     121
    grads_min:      06z16nov2023
    grads_step:     1hr
    units:          days since 1-1-1 00:00:0.0
    long_name:      time
    minimum:        06z16nov2023
    maximum:        06z21nov2023
    resolution:     0.041666668
```
If you know the times will always have a certain precision from this data source (e.g. maybe they will always have at least a round number of seconds), you could consider [rounding the times](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.dt.round.html) before proceeding with any time slicing:
```
>>> ds = xr.open_dataset(url)
>>> ds["time"] = ds.time.dt.round("s")
>>> ds.head(time=10).time
<xarray.DataArray 'time' (time: 10)>
array(['2023-11-16T06:00:00.000000000', '2023-11-16T07:00:00.000000000',
       '2023-11-16T08:00:00.000000000', '2023-11-16T09:00:00.000000000',
       '2023-11-16T10:00:00.000000000', '2023-11-16T11:00:00.000000000',
       '2023-11-16T12:00:00.000000000', '2023-11-16T13:00:00.000000000',
       '2023-11-16T14:00:00.000000000', '2023-11-16T15:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2023-11-16T06:00:00 ... 2023-11-16T15:00:00
Attributes:
    grads_dim:      t
    grads_mapping:  linear
    grads_size:     121
    grads_min:      06z16nov2023
    grads_step:     1hr
    long_name:      time
    minimum:        06z16nov2023
    maximum:        06z21nov2023
    resolution:     0.041666668
```

**Comment by stackjohn** [comment] 2023-11-18 23:01
@spencerkclark That has solved my issue 🙇 

Thank you!

You're theory seems sound with regards to float encoding. I'm not sure this is something that can be solved as a part of xarray. Perhaps this issue should be closed?

Thanks again and I appreciate the swift response from you both.

**Comment by spencerkclark** [comment] 2023-11-19 11:45
@stackjohn no problem!  Indeed I'm afraid there is not that much more that can be done from an xarray perspective.  This is an issue with the way the underlying data is stored, so a manual data cleaning step is necessary (fortunately it's not too painful in this case).  I'm going to go ahead and close this issue, but feel free to ask additional questions as necessary.

**Closed by spencerkclark** 2023-11-19 11:45 UTC
Labels: needs triage
