### ISSUE TITLE
Feature requests for DataArray.rolling

### ISSUE THREAD

**Issue by fjanoos** [pydata/xarray#3330] opened 2019-09-21 18:58 UTC
In `DataArray.rolling` it would be really nice to have support for window sizes specified in the units of the dimension (esp. time). For example if `da` has dimensions ```(time, space, feature)``` with `time` as `DatetimeIndex` - then it should be possible specificy  `da.rolling( time=pd.Timedelta( 100, 'D') )` as a valid window

**Comment by dcherian** [comment] 2021-07-08 16:29
Closing as duplicate of #3216

**Closed by dcherian** 2021-07-08 16:29 UTC
Labels: topic-rolling
