### ISSUE TITLE
Circular longitude axis

### ISSUE THREAD

**Issue by j08lue** [pydata/xarray#623] opened 2015-10-12 13:56 UTC
A common issue with global data or model output is that the zonal grid boundary might cut right through a region of interest. In that case, the field must be re-wrapped/shifted such that a region in the far east of the field is placed to the left of a region in the far west.

An way of achieving this when using `xray` (or `netCDF4`) I found was to use indices for `isel` that start somewhere in the east and then jump to 0 and continue from there. 

But this works only on data that is already loaded into memory (e.g. with `.load()`), as illustrated in [this gist](https://gist.github.com/j08lue/45635b0394d6c32ad4e7#file-xray_irregular_slice_before_load-ipynb). I assume that this constraint is due to the netCDF backend (in this case `netCDF4`) not supporting irregular slicing. Once loaded, the operation is performed on NumPy arrays, I guess?

Now the first thing is that it took me quite a while to figure out why this worked in some cases and not in others. Perhaps the `IndexError` that is thrown by the backend could be caught to give more hints on this? Or add a note in the [Docs](http://xray.readthedocs.org/en/stable/indexing.html) about this?

It would of course be great if `xray` had a nice high-level function to handle circular axes. Another item for the wish list...

(By the way, in Ferret this is called [Modulo Axes](http://ferret.pmel.noaa.gov/Ferret/documentation/users-guide/Grids-Regions/REGIONS#Chapter4-Modulo_axes).)

**Comment by jhamman** [comment] 2015-10-12 16:24
@j08lue - 

> But this works only on data that is already loaded into memory (e.g. with .load()), as illustrated in this gist. I assume that this constraint is due to the netCDF backend (in this case netCDF4) not supporting irregular slicing. Once loaded, the operation is performed on NumPy arrays, I guess?

We've recently addressed this in netCDF4 (issue: https://github.com/Unidata/netcdf4-python/issues/467, PR: https://github.com/Unidata/netcdf4-python/issues/469).  

> Now the first thing is that it took me quite a while to figure out why this worked in some cases and not in others. Perhaps the IndexError that is thrown by the backend could be caught to give more hints on this? Or add a note in the Docs about this?

We've also added a more descriptive error message on the xray end (#593, #595).  These changes will be available in xray 0.6.1 which should be released soon (blocked by read the docs bug).

As for your actual feature request.  Maybe you could show us some sample code that does what you're looking for?

**Comment by j08lue** [comment] 2015-10-13 14:17
@jhamman You guys seem to be always ahead of me - which is great! (I just did not notice it this time before I raised the issue...)

But it would actually not be that hard to make selecting regions across the boundary of a circular dimension more convenient in `xray`.

It would of course be great if it worked with real coordinate (longitude) values:

    ds.sel(lon=slice(-90, 15))

which, however, only works if the axis explicitly covers this range (e.g. has range -180E to 180E). If it ranges, say, from 0E to 360E, an empty DataArray is returned. There is no nice way of resolving this, I guess, because you would need to hard-code 360 or have it as a clumsy, non-CF-standard parameter and transform all values to some common range before trying to find the requested region.

But it should be less problematic with

    ds.isel(lon=slice(-100, 200))

i.e. `isel` with negative slice start. As it is now, this also returns an empty DataArray for me (xray 0.6.0), which is in a way consistent with the `sel` behaviour. But asking for negative indices is actually a quite pythonic way of implying circular. So could this be implemented, now that netCDF4 supports non-contiguous indexing?

**Comment by shoyer** [comment] 2015-10-13 19:11
I think we need another way of spelling this sort of selection that clearly disambiguates it from slicing. The problem is selection with a `slice` object (as it currently works) [always returns a view](http://xray.readthedocs.org/en/stable/indexing.html#copies-vs-views), but that's not possible for selections that wrap around a coordinate.

**Comment by j08lue** [comment] 2015-10-14 07:33
Alright, I see. In that case we should not create an entirely new syntax for this - unless there are more people than just me interested in this feature. I can just use my own little convenience function that generates a series of array indices that can be fed to `isel`, something like this:

```python
def wrap_iselkw(ds, dim, istart, istop):
    """Returns a kw dict for indices from `istart` to `istop` that wrap around dimension `dim`"""
    n = len(ds[dim])
    if istart > istop:
        istart -= n
    return { dim : np.mod(np.arange(istart, istop), n) }
```

**Comment by MaximilianR** [comment] 2016-12-23 18:46
Can this be closed @shoyer ?

**Comment by shoyer** [comment] 2016-12-24 00:11
Yeah, let's close this. This could be worth putting in some sort of geo-specific extension but it probably doesn't make sense for core xarray.

**Closed by shoyer** 2016-12-24 00:11 UTC

**Comment by gabrielmpp** [comment] 2019-06-20 20:07
Hi guys, have you ever implemented this feature anywhere in xarray or associated libraries?
