### ISSUE TITLE
xarray objects to not implement dask sizeof protocol `__sizeof__`

### ISSUE THREAD

**Issue by fjetter** [pydata/xarray#9088] opened 2024-06-10 17:20 UTC
### What happened?

I noticed that dask is not able to infer sizes of xarray collections when stored in memory. I was able to observe this in a `map_blocks` operation.

If dask cannot infer sizes of objects correctly this can have all sorts of bad implications for performance and stability, e.g. fetching too much data and overloading a worker.

### Minimal Complete Verifiable Example

```Python
import numpy as np
import xarray as xr
from datetime import date
from scipy import stats
from typing import Optional
import numpy as np

time = xr.cftime_range(
    start="2020-01-01", end="2021-12-31", freq="D", calendar="noleap"
)

dat = (
    xr.DataArray(
        np.random.random((len(time), )),
        dims=["time"],
        coords={"time": time},
    )
    .rename("foo")
    .to_dataset()
)

from dask.sizeof import sizeof

# This shows the actual size of the numpy array in memory (that's implemented by dask)
sizeof(dat.foo.data)
# 5840

# This is merely printing the size of the python object which is next to nothing
sizeof(dat.foo)
# 96
sizeof(dat)
# 112
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Anything else we need to know?

A possible way to implement this is by implementing a `__size__` method for the classes such that every class can define itself what it's in-memory size is.

Alternatively, this can be implemented by registering a function to `dask.sizeof.sizeof`. Incomplete examples of this

```python
import sys
from dask.sizeof import sizeof

@sizeof.register(xr.DataArray)
def xarray_sizeof_da(obj):
    return sys.getsizeof(obj) + sizeof(obj.coords) + sizeof(obj.data)

@sizeof.register(xr.Variable)
def xarray_sizeof_ds(obj):
    return sys.getsizeof(obj) + sizeof(obj._dims) + sizeof(obj._data)+ sizeof(obj._attrs) + sizeof(obj._encoding)
    
@sizeof.register(xr.Dataset)
def xarray_sizeof_ds(obj):
    return sys.getsizeof(obj) + sizeof(list(dat.variables.items()))
```

This could either be implemented in xarray (either way, whatever you prefer) where you likely have better expertise in defining this properly or we could register this lazily in dask instead.

### Environment

<details>

</details>

**Comment by max-sixty** [comment] 2024-06-10 17:22
Dupe of https://github.com/pydata/xarray/issues/5764

**Closed by max-sixty** 2024-06-10 17:22 UTC
Labels: bug, needs triage
