### ISSUE TITLE
inconsistent time coordinates types 

### ISSUE THREAD

**Issue by aurghs** [pydata/xarray#2196] opened 2018-05-29 16:14 UTC
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd
import xarray as xr

time = np.arange('2005-02-01', '2007-03-01', dtype='datetime64')
arr = xr.DataArray(
    np.arange(time.size), coords=[time,], dims=('time',), name='data'
)
arr.resample(time='M').interpolate('linear')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-6a92b6afe08e> in <module>()
      7     np.arange(time.size), coords=[time,], dims=('time',), name='data'
      8 )
----> 9 arr.resample(time='M').interpolate('linear')

~/devel/c3s-cns/venv_op/lib/python3.6/site-packages/xarray/core/resample.py in interpolate(self, kind)
    108 
    109         """
--> 110         return self._interpolate(kind=kind)
    111 
    112     def _interpolate(self, kind='linear'):

~/devel/c3s-cns/venv_op/lib/python3.6/site-packages/xarray/core/resample.py in _interpolate(self, kind)
    218             elif self._dim not in v.dims:
    219                 coords[k] = v
--> 220         return DataArray(f(new_x), coords, dims, name=dummy.name,
    221                          attrs=dummy.attrs)
    222 

~/devel/c3s-cns/venv_op/lib/python3.6/site-packages/scipy/interpolate/polyint.py in __call__(self, x)
     77         """
     78         x, x_shape = self._prepare_x(x)
---> 79         y = self._evaluate(x)
     80         return self._finish_y(y, x_shape)
     81 

~/devel/c3s-cns/venv_op/lib/python3.6/site-packages/scipy/interpolate/interpolate.py in _evaluate(self, x_new)
    632         y_new = self._call(self, x_new)
    633         if not self._extrapolate:
--> 634             below_bounds, above_bounds = self._check_bounds(x_new)
    635             if len(y_new) > 0:
    636                 # Note fill_value must be broadcast up to the proper size

~/devel/c3s-cns/venv_op/lib/python3.6/site-packages/scipy/interpolate/interpolate.py in _check_bounds(self, x_new)
    664                              "range.")
    665         if self.bounds_error and above_bounds.any():
--> 666             raise ValueError("A value in x_new is above the interpolation "
    667                              "range.")
    668 

ValueError: A value in x_new is above the interpolation range.
```
#### Problem description
The internal format of _arr.time_ is  datetime64[D]

```python
arr.time 

<xarray.DataArray 'time' (time: 758)>
array(['2005-02-01', '2005-02-02', '2005-02-03', ..., '2007-02-26',
       '2007-02-27', '2007-02-28'], dtype='datetime64[D]')
Coordinates:
  * time     (time) datetime64[D] 2005-02-01 2005-02-02 2005-02-03 ...
```
Internally there is a cast to float,  for both the old time indices **_x_** and the new time indices **_new_x_**, but the new time indices are in  datetime64[ns], so they don't match.

DataArrayResample._interpolate

```python
       x = self._obj[self._dim].astype('float')
       y = self._obj.data

       axis = self._obj.get_axis_num(self._dim)

       f = interp1d(x, y, kind=kind, axis=axis, bounds_error=True,
                    assume_sorted=True)
       new_x = self._full_index.values.astype('float')
```
With a cast to datetime64[ns]  it works:

```python
import numpy as np
import pandas as pd
import xarray as xr

time = np.arange('2005-02-01', '2007-03-01', dtype='datetime64').astype('datetime64[ns]')
arr = xr.DataArray(
    np.arange(time.size), coords=[time,], dims=('time',), name='data'
)
arr.resample(time='M').interpolate('linear')
<xarray.DataArray 'data' (time: 25)>
array([ 27.,  58.,  88., 119., 149., 180., 211., 241., 272., 302., 333., 364.,
       392., 423., 453., 484., 514., 545., 576., 606., 637., 667., 698., 729.,
       757.])
Coordinates:
  * time     (time) datetime64[ns] 2005-02-28 2005-03-31 2005-04-30 ...
```

#### Expected Output

```python
<xarray.DataArray 'data' (time: 25)>
array([ 27.,  58.,  88., 119., 149., 180., 211., 241., 272., 302., 333., 364.,
       392., 423., 453., 484., 514., 545., 576., 606., 637., 667., 698., 729.,
       757.])
Coordinates:
  * time     (time) datetime64[ns] 2005-02-28 2005-03-31 2005-04-30 ...
```

#### Output of ``xr.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

xarray: 0.10.4
pandas: 0.20.3
numpy: 1.13.1
scipy: 1.0.0
netCDF4: 1.3.1
h5netcdf: None
h5py: None
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: 0.16.1
distributed: None
matplotlib: 2.0.2
cartopy: None
seaborn: None
setuptools: 38.4.0
pip: 10.0.1
conda: None
pytest: 3.4.0
IPython: 6.1.0
sphinx: None
</details>

**Comment by keewis** [comment] 2020-03-29 13:40
I can't reproduce this error using the example. I guess this was fixed in the meantime?

**Closed** 2020-03-29 14:09 UTC
