### ISSUE TITLE
Better error message when reading netCDF4 file and netCDF4 not installed

### ISSUE THREAD

**Issue by clarkfitzg** [pydata/xarray#497] opened 2015-07-27 21:07 UTC
Trying to load a file without netcdf4 dependency:

```
xray.open_dataset('20150629_ave_mrr.nc')

...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/clark.fitzgerald/projects/mrr/june29_analysis.py in <module>()
      7 import xray
      8
----> 9 mrr = xray.open_dataset('20150629_ave_mrr.nc')

/Users/clark.fitzgerald/anaconda/envs/xray_dev/lib/python2.7/site-packages/xray-0.5.2_98_g69f7386-py2.7.egg/xray/backends/api.pyc in open_dataset(filename_or_obj, group, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, engine, chunks, lock)
    166                 store = backends.NetCDF4DataStore(filename_or_obj, group=group)
    167             elif engine == 'scipy':
--> 168                 store = backends.ScipyDataStore(filename_or_obj)
    169             elif engine == 'pydap':
    170                 store = backends.PydapDataStore(filename_or_obj)

/Users/clark.fitzgerald/anaconda/envs/xray_dev/lib/python2.7/site-packages/xray-0.5.2_98_g69f7386-py2.7.egg/xray/backends/scipy_.pyc in __init__(self, filename_or_obj, mode, format, group, writer, mmap)
     95             filename_or_obj = BytesIO(filename_or_obj)
     96         self.ds = scipy.io.netcdf_file(
---> 97             filename_or_obj, mode=mode, mmap=mmap, version=version)
     98         super(ScipyDataStore, self).__init__(writer)
     99

/Users/clark.fitzgerald/anaconda/envs/xray_dev/lib/python2.7/site-packages/scipy/io/netcdf.pyc in __init__(self, filename, mode, mmap, version)
    216
    217         if mode == 'r':
--> 218             self._read()
    219
    220     def __setattr__(self, attr, value):

/Users/clark.fitzgerald/anaconda/envs/xray_dev/lib/python2.7/site-packages/scipy/io/netcdf.pyc in _read(self)
    506         if not magic == b'CDF':
    507             raise TypeError("Error: %s is not a valid NetCDF 3 file" %
--> 508                             self.filename)
    509         self.__dict__['version_byte'] = fromstring(self.fp.read(1), '>b')[0]
    510

TypeError: Error: 20150629_ave_mrr.nc is not a valid NetCDF 3 file
```

It would be more helpful to suggest that the user install netcdf4.

**Comment by Yafei777** [comment] 2016-06-02 06:16
Cool! You saved my time! Thank you!

I just downloaded an nc file from noaa's esrl, and tried to read it using xarray, but it gave me the error message you mentioned above.

**Comment by liyi-1989** [comment] 2016-11-14 20:54
I got similar errors with xarray 0.8.2. Any solution for this error? Just use `import netCDF4`? (I can read the nc file in R)

**Comment by shoyer** [comment] 2016-11-14 21:12
You need to install [netcdf4-python](https://github.com/Unidata/netcdf4-python), e.g., `conda install netcdf4`.

**Comment by liyi-1989** [comment] 2016-11-14 21:13
Thanks @shoyer !

**Comment by fmaussion** [comment] 2016-11-14 21:16
Should we close this issue? ``is not a valid NetCDF 3 file`` is the best xarray can do I guess, since the error comes from scipy.

**Comment by shoyer** [comment] 2016-11-14 21:23
That error message is from SciPy. In principle, we could definitely inspect the first few bytes of the file and detect whether we have an appropriate read library install.

**Closed** 2017-05-25 02:06 UTC

**Comment by geetg** [comment] 2019-02-01 15:20
> You need to install [netcdf4-python](https://github.com/Unidata/netcdf4-python), e.g., `conda install netcdf4`.

Hi @shoyer, I'm using v0.11.2 (also tried v0.11.3), but I am unable to open my NC file. I get this same error and asks me to install netcdf4, which is already installed and up to date. I could open the before I had upgraded xarray to v0.11.3. Now, even back with the old version, I am unable to open it. As I'm still a beginner, I am unable to figure out what exactly the problem is. Thanks in advance.
