### ISSUE TITLE
Ability to Pass Dask Arrays as `data` in DataArray Creation

### ISSUE THREAD

**Issue by AyrtonB** [pydata/xarray#4650] opened 2020-12-05 11:33 UTC
**Is your feature request related to a problem? Please describe.**

I'm trying to convert a dask dataframe into a dask xarray without having to load the data fully into memory.

I was hoping I'd be able to pass `df.values` which is a Dask array to the `data` parameter in `xr.DataArray`

```python
idx_dim = 'datetime'
col_dim = 'fueltypes'

xr.DataArray(df.values, [df.index, df.columns], [idx_dim, col_dim])
```

However this raises the error: `ValueError: conflicting sizes for dimension 'datetime': length nan on the data but length 90386 on coordinate 'datetime'`

<br>

**Describe the solution you'd like**

An ability to create DataArrays from dask dataframes, similar to the existing reverse method for converting Datasets to dask dataframes: `Dataset.to_dask_dataframe`

<br>

**Describe alternatives you've considered**

I tried using `xr.Dataset.from_dataframe(df)` but it required the dataframe to be fully loaded into memory

Additionally, unlike the standard Pandas dataframe the Dask dataframe does not have a  `.to_xarray` method.

<br>

**Additional context**

This is in part made necessary by the decision of the Zarr developers to not support saving of dask dataframes to zarr, instead suggesting that you convert to an xarray and then save that to zarr.

**Comment by keewis** [comment] 2020-12-05 13:12
duplicate of #3929

As stated there and in dask/dask#6058, we would need to add a `Dataset.from_dask_dataframe` method which `dask.dataframe` could then wrap in a `to_xarray` method. This is currently only partially possible because we don't allow `dask.array` in dimension coordinates, but I guess it would be good to at least have partial support.

**Comment by keewis** [comment] 2020-12-05 13:13
As stated there and in dask/dask#6058, we would need to add a `Dataset.from_dask_dataframe` method which `dask.dataframe` could then wrap in a `to_xarray` method. This is currently only partially possible because we don't allow `dask.array` in dimension coordinates, but I guess it would be good to at least have partial support.

**Closed** 2020-12-05 13:13 UTC

**Comment by AyrtonB** [comment] 2020-12-05 17:09
Thanks, I saw [dask/dask#6058](https://github.com/dask/dask/issues/6058) but missed [#3929](https://github.com/pydata/xarray/issues/3929).

If I'm understanding you correctly there should be no problem passing a dask array for the data parameters its just the dims/coords. If the `_infer_coords_and_dims` method on DataArrays was adapted to check for any dask.delayed elements and compute them would that enable this functionality or are there additional blockers? Thanks for your help with this.

**Comment by AyrtonB** [comment] 2020-12-05 18:23
Have started to implement this but will continue the discussion in [3929](https://github.com/pydata/xarray/issues/3929#issuecomment-739330558)
