### ISSUE TITLE
Using the html repr in the documentation

### ISSUE THREAD

**Issue by OriolAbril** [pydata/xarray#6620] opened 2022-05-18 16:53 UTC
### What is your issue?

most (if not all) of xarray documentation is written as rst files and using the ipython directive. Due to this, the html repr is not use in the documentation. I find the html repr to be much more informative and intuitive, especially for beginners and I think it would be great to use it in the documentation. There are multiple ways to do this (not necessarly incompatible between them):

* Use [jupyter sphinx](https://jupyter-sphinx.readthedocs.io/en/latest/) instead of ipython to run and embed code cells from rst files. I use this in the documentation of [xarray-einstats](https://einstats.python.arviz.org/en/latest/api/generated/xarray_einstats.stats.median_abs_deviation.html) for example
* Use jupyter notebooks instead of rst. We use this in [arviz](https://python.arviz.org/en/latest/getting_started/WorkingWithInferenceData.html) and [xarray-einstats](https://einstats.python.arviz.org/en/latest/tutorials/stats_tutorial.html) docs. However, in order to keep using all the sphinx roles and directives used the [sphinx configuration](https://github.com/pydata/xarray/blob/main/doc/conf.py#L80) would need to be modified to use [myst-nb](https://myst-nb.readthedocs.io/en/latest/) instead of nbsphinx
* Use myst notebooks instead or rst. Also used in [ArviZ](https://python.arviz.org/en/latest/user_guide/plots_arguments_guide.html), also needs myst-nb instead of nbsphinx.

afaik, nbsphinx can be changed with myst-nb without needing to do any changes to the documentation, then rst files could be progressively updated to ipynb, myst or any other format supported by [jupytext](https://myst-nb.readthedocs.io/en/latest/authoring/custom-formats.html#using-jupytext), rst, markdown and notebook sources can all be used at the same time to generate the documentation and link from one to the other with sphinx roles and cross references.

Is this something that sounds interesting? I could update the infrastructure at some point whenever I have time and update a page (to any or multiple of the options above) as an example and then let other people take over

**Comment by TomNicholas** [comment] 2022-05-18 17:46
I think this would be really nice, but would defer to others' opinion on the best way to implement it.

**Comment by dcherian** [comment] 2024-09-24 05:31
dupe of #3893 and #7924

**Closed by dcherian** 2024-09-24 05:31 UTC
Labels: topic-documentation
