### ISSUE TITLE
array-api-strict v2.1.2 breaks CI

### ISSUE THREAD

**Issue by kmuehlbauer** [pydata/xarray#9750] opened 2024-11-08 07:25 UTC
### What is your issue?

`array-api-strict v2.1.2` (released some hours ago) needs `numpy >=2.1`, but the conda-forge package is missing that pin:

see: 
- https://github.com/conda-forge/array-api-strict-feedstock/issues/13
- https://github.com/conda-forge/array-api-strict-feedstock/pull/14

Some of xarray's dependencies are not available yet for numpy >=2.1, the current environments resolve to numpy 2.0.2. This breaks the tests where array-api-strict is imported.

**Comment by kmuehlbauer** [comment] 2024-11-08 08:23
The offending package is `numba` which has pinned numpy <2.1 for the current version 0.60. 

numba 0.61 will be numpy 2.1 compatible, but isn't yet released.

One short-term solution to unlock CI would be to pin numpy <2.1 in all CI with environments containing numba.

**Comment by keewis** [comment] 2024-11-08 08:46
you mean, pin `array-api-strict` for now?

**Comment by kmuehlbauer** [comment] 2024-11-08 08:51
That would be one solution, or to pin numpy>=2,<2.1. Not sure what's more reasonable.

**Comment by keewis** [comment] 2024-11-08 09:01
if I understand correctly, the issue is that the new version of `array-api-strict` requires `numpy>=2.1` but the `conda-forge` package metadata does not reflect that. So I don't think requiring an older version of `numpy` would help, since we'd still get the new (broken) version of `array-api-strict`.

**Comment by rgommers** [comment] 2024-11-08 09:56
The conda-forge `array-api-strict` metadata is fixed now.

If the current choice is to pin `array-api-strict` or `numpy`, I'd constrain the former though.

**Comment by keewis** [comment] 2024-11-08 10:07
`numpy` is indirectly constrained by `numba`, so if the metadata has been fixed there might be nothing we need to do here?

**Comment by kmuehlbauer** [comment] 2024-11-08 10:10
Thanks @rgommers, much appreciated.

@keewis The all-but-numba check fails even with numpy=2.1.3 and array-api-strict=2.1.2. See https://github.com/pydata/xarray/actions/runs/11739187309/job/32703227103?pr=9751

**Comment by keewis** [comment] 2024-11-08 10:13
I'll look into it, but this might take some time.

**Comment by kmuehlbauer** [comment] 2024-11-08 10:45
@keewis I've pinned `array-api-strict<=2.1` in all relevant environments in #9751. Would be good to get this in to unlock CI again. Would also buy you some time to investigate the issues wrt the failing array-api-strict related tests.

**Closed** 2024-11-11 10:05 UTC
Labels: bug, upstream issue, CI
