### ISSUE TITLE
Should an `apply` method exist for `DataArray` similar to the definition for `Dataset`?

### ISSUE THREAD

**Issue by pwolfram** [pydata/xarray#1450] opened 2017-06-12 15:51 UTC
The method `apply` is defined for `Dataset`.  Is there a design reason why it is not defined for `DataArray`?  In general I think it would be good to have calculation methods apply to both `Dataset` and `DataArray` as possible but am thinking I'm missing a key design element here.

**Comment by fmaussion** [comment] 2017-06-12 15:58
Probably a duplicate of https://github.com/pydata/xarray/issues/1074 ?

**Comment by shoyer** [comment] 2017-06-13 00:35
Yes, see discussion in #1074

**Closed by shoyer** 2017-06-13 00:35 UTC

**Comment by pwolfram** [comment] 2017-06-13 14:14
Thanks @fmaussion and @shoyer, sorry about the duplicated issue...
