### ISSUE TITLE
Automatic naming causes trouble

### ISSUE THREAD

**Issue by randolf-scholz** [pydata/xarray#2841] opened 2019-03-22 13:53 UTC
#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
from xarray import Dataset, DataArray
ds = Dataset(coords={'foo':[1,2,3], 'bar':[1,2,3]})
da = DataArray([0], dims='test')
da.name = 'abc'
ds[(1,2)] = da
print(da.name)
print(ds[(1,2)].name)
print(type(ds[(1,2)].name))
print(ds[(1,2)])              # throws error
```
#### Problem description

The name gets overwritten with the tuple key, but is should stay intact?!?
Secondly the print statement throws an error because internally `name_str = '%r ' % arr.name` is called. But here `arr.name` is a `tuple` !! 

Instead, it should be `repr(arr.name)` or `F"{arr.name}"`

#### Expected Output

The name should not change. 

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.18.0-16-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.1

xarray: 0.12.0
pandas: 0.24.2
numpy: 1.16.2
scipy: 1.2.1
netCDF4: 1.4.2
pydap: None
h5netcdf: None
h5py: 2.9.0
Nio: None
zarr: None
cftime: 1.0.3.4
nc_time_axis: None
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.2.1
dask: None
distributed: None
matplotlib: 3.0.3
cartopy: None
seaborn: None
setuptools: 40.8.0
pip: 19.0.3
conda: 4.6.8
pytest: None
IPython: 7.3.0
sphinx: 1.8.5

</details>

**Comment by shoyer** [comment] 2019-03-22 16:54
Thanks for the report.

Yes, this looks like a bug. A pull request to fix this would be very welcome.

**Comment by randolf-scholz** [comment] 2019-03-25 10:47
@shoyer I had a look at xarray/core/formatting.py and it seems like there are a couple of places where keys get formatted this way. That is `%`-style formatting is used, ignoring the possibility that a `dict` key may be of type `tuple`. Personally I am really a big fan of `f-strings`, as they are faster and more readable than `%`-style formatting. They would in my opinion be one of the best ways fix this error and prevent it from happening again in the future.

Using them would  of course mean dropping python 3.5 support.

**Comment by shoyer** [comment] 2019-03-25 15:09
I also love fstrings, but I don't think we're ready to drop Python 3.5 support yet. Let's try explicit calls to `.format()` for now.

**Comment by keewis** [comment] 2021-01-25 22:05
the formatting of the tuple-typed key works now (#2906), so I'm closing this.

The name of `da` is still dropped, but that is intended behavior (it also happens with `ds["def"] = da`). For a discussion about what to do with tuple-typed keys see #4821.

**Closed by keewis** 2021-01-25 22:05 UTC
Labels: bug
