### ISSUE TITLE
CFMaskCoder creates unnecessary copy for `uint16` variables

### ISSUE THREAD

**Issue by davidorme** [pydata/xarray#6733] opened 2022-06-28 08:38 UTC
### What is your issue?

Hi,

I have a bunch of global gridded data as a 20 year sequence of daily Matlab files that I am consolidating into annual netcdfs using `xarray`. The dataset is a reasonably big DataArray (7200 x 3600 x 365, for ~35GB  as `float32`), but compiling the data into a `numpy` array and then creating a DataArray and writing using `to_netcdf` works fine with `float32`. However, I've been implementing encoding the data using `uint16` to save disk space - the range of the data and actual precision mean that this seems reasonable. I've been using the docs as a reference:

https://docs.xarray.dev/en/stable/user-guide/io.html#scaling-and-type-conversions

The problem I then get is that the memory usage spikes unpredictably. I've been using `psutil` to track the process memory in the script:

```python
def report_mem(process, prefix=''):

    mem = process.memory_info()[0] / float(2 ** 30)
    sys.stdout.write(f"{prefix}Memory usage: {mem}\n")
    sys.stdout.flush()
```

The actual data ingestion and creation of the DataArray seems to be absolutely fine. With the DataArray created, the overall process memory of 35.69GB  as expected. 

```python
xds = xarray.DataArray(
    base_grid,  # 365 x 3600 x 7200 np.array with dtype `float32`
    coords=[dates, latitude, longitude],
    dims=["time", "latitude", "longitude"],
    name=canonical_name,
    attrs={"units": unit},
)
```

The next bit of the script is then:

```python
if pack:
    encoding = {
        canonical_name: {
            "zlib": True,
            "complevel": 6,
            "dtype": "uint16",
            "scale_factor": scale_factor,
            "_FillValue": 65535,
        }
    }
else:
    encoding = {canonical_name: {"zlib": True, "complevel": 6}}

xds.to_netcdf(out_file, encoding=encoding)
```

When `pack=False`, the data is written out as `float32` and the reported peak memory usage for the job is 37GB.  However, when `pack=TRUE`, I get an unpredictable increase in memory usage. I was anticipating that another ~17GB could be needed to hold a `uint16` version of the array, but what I see is a huge and variable increase in memory use. 

The list below shows the job reported memory usage for one test run of the script over 19 years. The first number in the list below is the peak RAM usage in GB. I'm running these on an HPC cluster and anything over 96GB gets killed, so only a handful of these are actually completing, so it could be that the memory requirements might run even higher, but are getting killed. Another odd thing is that the files that complete are unpredictable - the memory usage is not stable for a particular year.

```
conversion_10.out: Used       :       115 (peak)   0.82 (ave)
conversion_11.out: Used       :        82 (peak)   0.88 (ave)
conversion_12.out: Used       :       106 (peak)   0.50 (ave)
conversion_13.out: Used       :       115 (peak)   0.50 (ave)
conversion_14.out: Used       :       124 (peak)   0.56 (ave)
conversion_15.out: Used       :        83 (peak)   0.84 (ave)
conversion_16.out: Used       :       124 (peak)   0.58 (ave)
conversion_17.out: Used       :        94 (peak)   0.87 (ave)
conversion_18.out: Used       :        82 (peak)   0.83 (ave)
conversion_19.out: Used       :       110 (peak)   0.82 (ave)
conversion_20.out: Used       :       106 (peak)   0.72 (ave)
conversion_21.out: Used       :       107 (peak)   0.80 (ave)
conversion_3.out: Used       :        83 (peak)   0.93 (ave)
conversion_4.out: Used       :       124 (peak)   0.70 (ave)
conversion_5.out: Used       :       130 (peak)   0.77 (ave)
conversion_6.out: Used       :       112 (peak)   0.68 (ave)
conversion_7.out: Used       :        80 (peak)   0.52 (ave)
conversion_8.out: Used       :        97 (peak)   0.85 (ave)
conversion_9.out: Used       :       117 (peak)   0.59 (ave)
```

The files that do run end up with exactly the expected structure:

```bash
(python3.10) []$ ncdump -h LAI_cf_uint16/LAI_2007.nc 
netcdf LAI_2007 {
dimensions:
	time = 365 ;
	latitude = 3600 ;
	longitude = 7200 ;
variables:
	int64 time(time) ;
		time:units = "days since 2007-01-01 00:00:00" ;
		time:calendar = "proleptic_gregorian" ;
	double latitude(latitude) ;
		latitude:_FillValue = NaN ;
	double longitude(longitude) ;
		longitude:_FillValue = NaN ;
	ushort leaf_area_index(time, latitude, longitude) ;
		leaf_area_index:_FillValue = 65535US ;
		leaf_area_index:units = "1" ;
		leaf_area_index:scale_factor = 0.00015625 ;
}
```

Any suggestions? It sounds like this should work!

## Python version and package versions

```
(python3.10) $ python --version
Python 3.10.4
(python3.10) $ pip list
Package           Version
----------------- ---------
Bottleneck        1.3.4
certifi           2022.6.15
cftime            1.5.1.1
mkl-fft           1.3.1
mkl-random        1.2.2
mkl-service       2.4.0
netCDF4           1.5.7
numexpr           2.8.1
numpy             1.22.3
packaging         21.3
pandas            1.4.2
pip               21.2.4
psutil            5.8.0
pyparsing         3.0.4
python-dateutil   2.8.2
pytz              2022.1
scipy             1.7.3
setuptools        61.2.0
six               1.16.0
typing_extensions 4.1.1
wheel             0.37.1
xarray            0.20.1

(python3.10) [dorme@login-c SNU_Ryu_FPAR_LAI]$ python
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xarray
>>> xarray.show_versions()
/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 4.18.0-348.20.1.el8_5.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: ('en_GB', 'UTF-8')
libhdf5: 1.10.6
libnetcdf: 4.6.1

xarray: 0.20.1
pandas: 1.4.2
numpy: 1.22.3
scipy: 1.7.3
netCDF4: 1.5.7
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.5.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.4
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
setuptools: 61.2.0
pip: 21.2.4
conda: None
pytest: None
IPython: None
sphinx: None
>>> 

```

**Comment by davidorme** [comment] 2022-06-28 09:37
I've also tried pre-converting the `float32` array to `uint16`:

```python
if pack:
    out_data =  np.round(base_grid * scale_factor, 0)
    out_data[np.isnan(out_data)] = 65535
    out_data = out_data.astype('uint16')
else:
    out_data = base_grid
```

I expect that to add that extra 17GB for a total memory of 53GB or so but then exporting to netcdf still shows unexpectedly variable peak memory use:

```bash
$ grep peak conversion_*
conversion_10.out: Used       :       133 (peak)   0.53 (ave)
conversion_11.out: Used       :       117 (peak)   0.73 (ave)
conversion_12.out: Used       :        92 (peak)   0.93 (ave)
conversion_13.out: Used       :       103 (peak)   0.75 (ave)
conversion_14.out: Used       :        79 (peak)   0.64 (ave)
conversion_15.out: Used       :        94 (peak)   0.66 (ave)
conversion_16.out: Used       :        92 (peak)   0.95 (ave)
conversion_17.out: Used       :       129 (peak)   0.66 (ave)
conversion_18.out: Used       :        92 (peak)   0.91 (ave)
conversion_19.out: Used       :       105 (peak)   0.67 (ave)
conversion_1.out: Used       :        77 (peak)   0.94 (ave)
conversion_20.out: Used       :        87 (peak)   0.65 (ave)
conversion_21.out: Used       :        93 (peak)   0.63 (ave)
conversion_2.out: Used       :        92 (peak)   0.95 (ave)
conversion_3.out: Used       :        92 (peak)   0.94 (ave)
conversion_4.out: Used       :        92 (peak)   0.93 (ave)
conversion_5.out: Used       :       121 (peak)   0.47 (ave)
conversion_6.out: Used       :        92 (peak)   0.94 (ave)
conversion_7.out: Used       :        92 (peak)   0.96 (ave)
conversion_8.out: Used       :        92 (peak)   0.93 (ave)
conversion_9.out: Used       :       129 (peak)   0.47 (ave)
```

One thing I do see for _some_ failing files in the script reporting  is this exception - the `to_netcdf` process appears to be creating another 32GB `float32` array?

```python
Data loaded; Memory usage: 35.70772171020508
Conversion complete; Memory usage: 53.329856872558594
Array created; Memory usage: 53.329856872558594
Traceback (most recent call last):
  File "/rds/general/project/lemontree/live/source/SNU_Ryu_FPAR_LAI/convert_SNU_Ryu_to_netcdf.py", line 162, in <module>
    xds.to_netcdf(out_file, encoding=encoding)
  File "/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/xarray/core/dataarray.py", line 2839, in to_netcdf
    return dataset.to_netcdf(*args, **kwargs)
  File "/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/xarray/core/dataset.py", line 1902, in to_netcdf
    return to_netcdf(
  File "/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/xarray/backends/api.py", line 1072, in to_netcdf
    dump_to_store(
  File "/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/xarray/backends/api.py", line 1119, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/xarray/backends/common.py", line 261, in store
    variables, attributes = self.encode(variables, attributes)
  File "/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/xarray/backends/common.py", line 350, in encode
    variables, attributes = cf_encoder(variables, attributes)
  File "/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/xarray/conventions.py", line 855, in cf_encoder
    new_vars = {k: encode_cf_variable(v, name=k) for k, v in variables.items()}
  File "/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/xarray/conventions.py", line 855, in <dictcomp>
    new_vars = {k: encode_cf_variable(v, name=k) for k, v in variables.items()}
  File "/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/xarray/conventions.py", line 269, in encode_cf_variable
    var = coder.encode(var, name=name)
  File "/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/xarray/coding/variables.py", line 168, in encode
    data = duck_array_ops.fillna(data, fill_value)
  File "/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/xarray/core/duck_array_ops.py", line 298, in fillna
    return where(notnull(data), data, other)
  File "/rds/general/user/dorme/home/anaconda3/envs/python3.10/lib/python3.10/site-packages/xarray/core/duck_array_ops.py", line 285, in where
    return _where(condition, *as_shared_dtype([x, y]))
  File "<__array_function__ internals>", line 180, in where
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 35.2 GiB for an array with shape (365, 3600, 7200) and data type float32
```

**Comment by dcherian** [comment] 2022-06-28 17:23
Yeah I think the issue is that the "CFMaskCoder" tries to repalce NaNs regardless of the dtype of the variable. Doing this creates a copy in this step: `where(notnull(data), data, other)`. 

You should set `FillValue` to None after manually encoding to ints to skip the extra copy.

We should  probably raise an error or at least a warning for integer dtypes and  not-None `FillValue`

**Comment by davidorme** [comment] 2022-06-28 19:20
Thanks for the quick response. 

I don't quite follow the process for the `FillValue`. If I manually encode as integer, setting NaN to `65535` as above, how would I ensure that the correct fill value is set in the resulting file? If I leave the `_FillValue = 65535` out of the encoding for `DataArray.to_netcdf`, then those values won't be interpreted correctly.

**Comment by dcherian** [comment] 2022-06-28 19:35
Try setting  `_FillValue` in attrs? I haven't triedf this...

**Comment by davidorme** [comment] 2022-06-28 20:02
Thanks again for your help! 

I think that is what I am doing. If I understand right:

### Using  `to_netcdf` to handle the encoding

* I'm passing a DataArray containing `float32` data.
* The `np.ndarray` containing the data can simply use `np.nan` to represent missing data.
* Using `to_netcdf` with an encoding to `uint16` has memory usage of 2 x float + 1 x int - set NaN on a copy and convert to int
* The other thing that is puzzling here is that 35GB * 2.5 (two `float32` copies + one `uint16` copy) is ~ 90GB but many of the processes are using much more than that.

### Manual encoding

* I'm passing a DataArray containing `uint16` data.
* However - as far as I can see - DataArray _itself_ doesn't specify an alternative missing data value. Because `np.nan` is a float, you can't represent missing data within an integer DataArray?
* So, I am using `_FillValue=65535` in the encoding to `to_netcdf`.
* But that still appears to be triggering the encoding step - the Traceback in my second comment was from a manually encoded `uint16` DataArray.

**Comment by dcherian** [comment] 2022-06-28 21:57
> So, I am using _FillValue=65535 in the encoding to to_netcdf.

`encoding` is really an instruction to Xarray to encode the data. But you've already done that. So specify `_FillValue` in `attrs` instead of `encoding`. This will get written to file and be interpreted on read. At least IIUC =)

**Comment by dcherian** [comment] 2022-06-29 15:41
> Where a cast is specified in encoding, could xarray not cast the data first to get that
isolated copy and then set the fill on the cast array?

If you cast float to int you might lose information neeeded to accurately do the filling step.

> the only possible gotcha here for users is
that data stored in a netcdf file as integer type data but with a _FillValue is loaded as a float using np.NaN because there is no np.nan equivalent for integer types.

Yes. but your data originated as floating point so this is correct.

> ncdump asserts that there has to be a missing data value, which is 65535 unless set
otherwise, but xarray is using the presence of the _FillValue attribute to signal the presence
of missing data.

You can specify `missing_value` and/or `_FillValue` attributes. So you could try that. Xarray does not follow the default "fill values" because it can be confusing; it is valid to store 65535 as u2 for example.

**Comment by davidorme** [comment] 2022-06-30 11:59
I still see strange memory spikes that kill my jobs but the behaviour is not reproducible - the conversion will fail with > 4x memory use and then succeed the next time with the same inputs. My guess is that this isn't anything to do with `xarray`, but noting it just in case.

**Comment by kmuehlbauer** [comment] 2023-09-13 12:43
@davidorme It  looks like you got along with it. I'm closing. Please reopen if needed.

**Closed by kmuehlbauer** 2023-09-13 12:43 UTC
Labels: topic-CF conventions
