### ISSUE TITLE
decode_cf

### ISSUE THREAD

**Issue by shaharkadmiel** [pydata/xarray#2970] opened 2019-05-17 09:41 UTC
To me this name is a bit confusing as it actually _encodes_ an in memory object to look like a _decoded_ netcdf file.

I have a class which inherits (I know about `dataset_accessor`, still seems easier to simply inherit...) ``xarray.Dataset`` to which I've added a method `_make_cf`:

```python
import xarray as xr
class XResult(xr.Dataset):
    def __init__(self, data=None, coords=None, attrs=None, **kwargs):
        if isinstance(data, str):
            kwargs = dict(READ_KWARGS, **kwargs)
            with xr.open_dataset(data, **kwargs) as data:
                attrs = data.attrs

        super().__init__(data, coords, attrs)
        self._make_cf()

    def _make_cf(self):
        self = xr.decode_cf(self)
```
I expect the XResult object to be _decoded_ but it is not.

if I do `xresult = xarray.decode_cf(XResult(...))` than the object is indeed _decoded_ but is no longer an `XResult` object and loses the attached functionality.

It would be quite convenient to have a `decode_cf` or `encode_cf` method part of the `Dataset` class that will operate inplace.

**Comment by keewis** [comment] 2020-03-29 14:02
I think this is actually a python issue:
```python
def _make_cf(self):
    self = xr.decode_cf(self)
```
since `self` is a variable name in python (by convention referring to the instance, but it is not treated different from other names), this
1. calculates `xr.decode_cf(self)` which returns a new dataset with decoded values
2. reassigns `self` to the result (so it does not refer to the class instance anymore)

So that while this was intended to be a inplace modification, it actually is the same as
```python
def _make_cf(self):
    xr.decode_cf(self)
```
and does not do anything to the object.

In cases like this, use either aggregation or the `register_dataset_accessor`.
Here's how this looks with aggregation:
```python
class XResult:
    def __init__(self, data=None, coords=None, attrs=None, **kwargs):
        if isinstance(data, str):
            kwargs = dict(READ_KWARGS, **kwargs)
            with xr.open_dataset(data, **kwargs) as data:
                attrs = data.attrs

        self._data = xr.Dataset(data, coords, attrs)
        self._make_cf(self._data)

    def _make_cf(self):
        self._data = xr.decode_cf(self._data)
```

**Closed by keewis** 2020-03-29 14:02 UTC
