### ISSUE TITLE
Interpolation loses edge points

### ISSUE THREAD

**Issue by rjp23** [pydata/xarray#7935] opened 2023-06-21 17:51 UTC
### What happened?

I'm not sure if this is a bug, normal behaviour or a feature request but if it's expected behaviour, it should be better documented.

I want to interpolate a 2D dataset to a finer spatial grid. I've put together a reproducible example based on the tutorial here: https://docs.xarray.dev/en/stable/user-guide/interpolation.html

The result is this:
<img width="1037" alt="Screenshot 2023-06-21 at 18 45 19" src="https://github.com/pydata/xarray/assets/31730876/2a0f5764-462d-4412-be20-1e45ed0f9e6d">

When I do this, the edge points are lost (as you can see on the west/north boundaries here).

### What did you expect to happen?

I'd expect the interpolation to protect the boundary points and not lose them.

### Minimal Complete Verifiable Example

```Python
ds = xr.tutorial.load_dataset("air_temperature")
subplot_kw = dict(projection=ccrs.PlateCarree())
new_lon = np.linspace(ds.lon[0], ds.lon[-1], ds.dims["lon"] * 4)
new_lat = np.linspace(ds.lat[0], ds.lat[-1], ds.dims["lat"] * 4)
dsi = ds.interp(lat=new_lat, lon=new_lon, method='nearest', kwargs={'fill_value':None})
          
fig, axes = plt.subplots(1, 2, figsize=(18, 12), subplot_kw=subplot_kw)
axes = np.ravel(axes)
          
ax = axes[1]
ds.air.isel(time=0).plot(x='lon', y='lat', ax=ax, add_colorbar=False)
ax.set_extent([ds.lon.min()-5., ds.lon.min()+20., ds.lat.max()-20, ds.lat.max()+5])
ax.coastlines()
          
ax = axes[0]
dsi.air.isel(time=0).plot(x='lon', y='lat', ax=ax, add_colorbar=False)
ax.set_extent([ds.lon.min()-5., ds.lon.min()+20., ds.lat.max()-20, ds.lat.max()+5])
ax.coastlines()
          
plt.show()
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1160.90.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.16.1
pandas: 1.1.3
numpy: 1.19.2
scipy: 1.5.2
netCDF4: 1.5.4
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.2.1
nc_time_axis: 1.2.0
PseudoNetCDF: None
rasterio: 1.1.8
cfgrib: None
iris: 2.4.0
bottleneck: None
dask: 2.30.0
distributed: 2.30.0
matplotlib: 3.3.2
cartopy: 0.18.0
seaborn: 0.11.0
numbagg: None
pint: None
setuptools: 49.6.0.post20201009
pip: 20.2.3
conda: None
pytest: None
IPython: 5.8.0
sphinx: None

</details>

**Comment by kmuehlbauer** [comment] 2024-06-11 12:03
@rjp23 Maybe you've already found a solution, but I'll anyway add some context here.

The issue is with the different resolution. If you increase resolution by a factor of four the lat/lon intervals will be reduced by four. As the data values are assumed as gridcell-center the size of the quadrilaterals is decreased, resulting in those differences in the two plots.

In your example the resolution is 2.5 for latitude and longitude. The centerpoint for the upper left quadrilateral is (lat: 75., lon: 200.). The upper left point of that quadrilateral is (lat: 75 + 2.5 / 2, lon: 200 - 2.5 / 2) -> (lat: 76.125, lon: 198.75). For the same plot using the factor of 4 in resolution this would be (lat: 75 + 0.625 / 2, lon: 200 - 0.625 / 2) -> (lat: 75.3125, lon: 199.6875).

If you want to create similar looking plots you would need to fix the interpolation to extend the ranges in both latitude and longitude.

**Comment by kmuehlbauer** [comment] 2024-06-11 13:13
I think there is nothing xarray can do about. It should be fixed in the users workflow. Please reopen if you think aotherwise.

**Closed by kmuehlbauer** 2024-06-11 13:13 UTC
Labels: bug, topic-plotting
