### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by MM-cyi** [pydata/xarray#7487] opened 2023-01-30 14:04 UTC
### What is your issue?

Hi. 

The data linked from 
`https://docs.xarray.dev/en/stable/examples/ROMS_ocean_model.html`
at
`http://barataria.tamu.edu/thredds/catalog.html?dataset=txla_hindcast_agg `
are unavailable. 

Any chance this could be fixed? 

Thanks. 
Marco

**Comment by keewis** [comment] 2023-01-30 14:07
this looks like a duplicate of #7486. Closing, but feel free to follow the discussion there.

**Closed by keewis** 2023-01-30 14:07 UTC
Labels: needs triage
