### ISSUE TITLE
Coordinate attributes are dropped when interpolating datasets

### ISSUE THREAD

**Issue by Illviljan** [pydata/xarray#4839] opened 2021-01-23 20:05 UTC
**What happened**:
When I was interpolating datasets I noticed that the coordinate variables disappeared.

**What you expected to happen**:
Coordinate attributes should be retained just like variables are.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import xarray as xr

names = np.core.defchararray.add("long_variable_name", np.arange(0, 2).astype(str))
coords = dict(time=np.array([0, 1]))
data_vars = dict()
for v in names:
    data_vars[v] = xr.Variable(
        "time", np.array([0, 1], dtype=int), attrs=dict(unit="kg")
    )
ds1 = xr.Dataset(data_vars=data_vars, coords=coords)
ds1.attrs = {
    k: 2 for k in np.core.defchararray.add("attr_", np.arange(0, 3).astype(str))
}
ds1.time.attrs.update(unit="s")

# Print time:
ds1.time
Out[115]: 
<xarray.DataArray 'time' (time: 2)>
array([0, 1])
Coordinates:
  * time     (time) int32 0 1
Attributes:
    unit:     s

# Interpolate:
ds1 = ds1.interp(
    time=np.array([0, 0.5, 1, 2]),
    assume_sorted=True,
    method="linear",
    kwargs=dict(fill_value="extrapolate"),
)

# Print interpolated time, units are lost:
ds1.time
Out[117]: 
<xarray.DataArray 'time' (time: 4)>
array([0. , 0.5, 1. , 2. ])
Coordinates:
  * time     (time) float64 0.0 0.5 1.0 2.
```

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
libhdf5: 1.10.4
libnetcdf: None

xarray: 0.16.2
pandas: 1.2.0
numpy: 1.17.5
scipy: 1.4.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2020.12.0
distributed: 2020.12.0
matplotlib: 3.3.2
cartopy: None
seaborn: 0.11.1
numbagg: None
pint: None
setuptools: 51.1.2.post20210112
pip: 20.3.3
conda: 4.9.2
pytest: 6.2.1
IPython: 7.19.0
sphinx: 3.4.3

</details>

**Comment by keewis** [comment] 2021-01-24 00:20
the reason for this is that `time` has actually been replaced with the coordinates you provided. You can verify this by passing in new attributes:
```python
ds1 = ds1.interp(
    time=("time", np.array([0, 0.5, 1, 2]), {"a": "b"}),
    assume_sorted=True,
    method="linear",
    kwargs=dict(fill_value="extrapolate"),
)
```
I'm not quite sure what to do here.

**Comment by dcherian** [comment] 2021-01-24 00:25
I think we can copy `attrs` over when provided anything that is not a `DataArray`?

**Comment by keewis** [comment] 2021-01-25 16:40
this might be a duplicate of #4239

**Closed** 2021-04-27 07:00 UTC
Labels: metadata
