### ISSUE TITLE
RTD failure on main

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#7434] opened 2023-01-12 15:57 UTC
### What happened?

[logs](https://readthedocs.org/projects/xray/builds/19149017/)
```
sphinx.errors.SphinxParallelError: RuntimeError: Non Expected exception in `/home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/7433/doc/user-guide/interpolation.rst` line 331
```

This seems real

**Comment by kmuehlbauer** [comment] 2023-01-12 16:19
XRef #7414

**Comment by keewis** [comment] 2023-01-12 19:51
I agree with @kmuehlbauer that this might be a duplicate of #7414: as detailed there, `scipy` changed something in the interpolation code in their most recent version, which is the cause of the errors here. That apparently has to do with a specific combination of `dtype`s, so I'm guessing that that's why we don't hit that bug in CI.

In any case, pinning the `scipy` version to a slightly older version should avoid that bug for now.

**Closed** 2023-01-13 17:38 UTC
Labels: bug, topic-documentation
