### ISSUE TITLE
.dt accessor returns int instead of float, resulting in misrepresentation of NaT values

### ISSUE THREAD

**Issue by idantene** [pydata/xarray#7928] opened 2023-06-19 21:46 UTC
### What happened?

With the latest xarray (this doesn't happen at least in version `2023.2.0`), accessing .dt parts returns a strict `int64` DataArray, resulting in wrongly presented missing values.

```python
In [2]: s = pd.to_datetime(pd.Series(['2021-12-01', pd.NaT]))

In [3]: s
Out[3]: 
0   2021-12-01
1          NaT
dtype: datetime64[ns]

In [4]: s.dt.year
Out[4]: 
0    2021.0
1       NaN
dtype: float64

In [5]: s.to_xarray()
Out[5]: 
<xarray.DataArray (index: 2)>
array(['2021-12-01T00:00:00.000000000',                           'NaT'],
      dtype='datetime64[ns]')
Coordinates:
  * index    (index) int64 0 1

In [6]: s.to_xarray().dt.year
Out[6]: 
<xarray.DataArray 'year' (index: 2)>
array([                2021, -9223372036854775808])
Coordinates:
  * index    (index) int64 0 1

```

Notice how:
1. The series and generated DataArray are both correctly `datetime64[ns]`
2. The series' `.dt.year` accessor returns a float64 to accommodate the missing value (it will use `int32` w/o the missing value).
3. The DataArray's `.dt.year` returns a negative integer instead of `nan`.

Additionally, compare with the same snippet's output with xarray 2023.2.0:
```python3
In [3]: s.to_xarray().dt.year
Out [3]:
<xarray.DataArray 'year' (index: 2)>
array([2021.,   nan])
Coordinates:
  * index    (index) int64 0 1
```

### What did you expect to happen?

The `.dt` accessor should return a float with missing values when needed.

### Minimal Complete Verifiable Example

```Python
import pandas as pd

s = pd.to_datetime(pd.Series(['2021-12-01', pd.NaT]))
s.to_xarray().dt.year
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
python-bits: 64
OS: Linux
OS-release: 5.19.0-1025-aws
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: None
libnetcdf: None

xarray: 2023.5.0
pandas: 2.0.2
numpy: 1.23.4
scipy: 1.10.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: 2023.6.0
distributed: 2023.6.0
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: 2023.6.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 59.6.0
pip: 23.1.2
conda: None
pytest: None
mypy: None
IPython: 8.14.0
sphinx: None

</details>

**Comment by idantene** [comment] 2023-06-19 22:15
FWIW I believe the source for this is the dtype changes in #7796

**Comment by kmuehlbauer** [comment] 2023-06-20 06:55
@idantene Thanks for bringing this to attention. I can reproduce and it seems the unconditional cast (as you suggested) is the cause:

https://github.com/pydata/xarray/blob/e739df7d27d88008f09a927fc0f61fccdc7a77aa/xarray/core/accessor_dt.py#L122

If `NaT` is present in the source data `access_method` will return `float64` with `nan`. The cast to `int64` will transform `nan` -> `-9223372036854775808`. I'm not really sure how and where to handle this, but one solution would be to check for presence of `NaT` or `float64` return type and do not cast in these occasions.

**Comment by idantene** [comment] 2023-06-20 07:05
Hey @kmuehlbauer, thanks for addressing and confirming the issue!

I think both of those are valid approaches, and would surely address the issue at hand. However, these feel a bit like stop-gap measures, and I have to wonder (as someone who hasn't contributed to xarray yet) - why are the type casts even necessary, especially in the series case?
It seems like it can be directly off-loaded to pandas.

**Comment by kmuehlbauer** [comment] 2023-06-20 07:15
From reading the linked PR I think the main thing was to cast `int32` to `int64` (for xarray internal use). @keewis and @dcherian surely have more insight into that topic.

**Comment by dcherian** [comment] 2023-06-21 21:14
Yes I think we should cast to float like pandas does.

**Comment by kmuehlbauer** [comment] 2023-06-22 05:59
@dcherian pandas currently returns `float64` in presence of `NaT` and `int32` otherwise. As mentioned above, should xarray cast only `int32` -> `int64` and keep the pandas `float64`? Or should we also cast to `int32` -> `float64`. Anyway, this would need to happen inside https://github.com/pydata/xarray/blob/4156ce53a8e4b65bbeaabebe0b2071d3d9b18c01/xarray/core/accessor_dt.py#L68 to also make this work for dask arrays.

Side note: If `isocalender` is requested, xarray will already cast to `int64` unconditionally.

**Comment by idantene** [comment] 2023-08-17 16:47
Any update on this @dcherian @kmuehlbauer?

We're stuck with `2023.2.0` because of this 😢

**Comment by kmuehlbauer** [comment] 2023-08-18 12:21
@idantene Thanks for checking back. I lost track over summer. I've a somewhat clumsy approach over in #8084. Would be great if you can test with your setup.

It checks for NaT and casts to float64 if that's the case. Unfortunately `isocalendar` needs special handling which requires NaT check twice for now. If anyone has suggestions to make this more slim, please comment in the PR.

**Comment by kmuehlbauer** [comment] 2023-08-21 06:58
@idantene @dcherian I think this problem should be fixed upstream. I've opened an issue  https://github.com/pandas-dev/pandas/issues/54657 over at pandas to see, if and how this can be aligned.

**Comment by idantene** [comment] 2023-08-21 07:13
Thanks @kmuehlbauer! I'll have a test run soon to verify this fix - it looks good on paper.

I'm curious as to how you'll fix this for dask, though it does not apply to our use case :D

**Comment by kmuehlbauer** [comment] 2023-08-21 07:34
> I'm curious as to how you'll fix this for dask, though it does not apply to our use case :D

I've no idea how this can be made consistent for dask without a priory knowledge if there are NaT involved or not. As far as I checked it will return some `RuntimeWarning: invalid value encountered in cast` warning, which will at least let the user know about the issue.

**Closed** 2023-09-14 13:57 UTC
Labels: bug, regression
