### ISSUE TITLE
Deep copy not deep?

### ISSUE THREAD

**Issue by whophil** [pydata/xarray#9775] opened 2024-11-13 04:21 UTC
### What happened?

I have a NetCDF file produced by an upstream process. After loading this into an xarray dataset and calling `DataSet.copy(deep=True)`, I find that some coordinates still share memory with the source of the copy.

The NetCDF file in question:
[data_clean.nc.zip](https://github.com/user-attachments/files/17726082/data_clean.nc.zip)

### What did you expect to happen?

I expected a deep copy to be deep, with no shared memory between.

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import numpy as np

ds = xr.load_dataset("/Users/philchiu/repos/spheres/tests/data_clean.nc")
ds2 = ds.copy(deep=True)

print(ds.variables["FREQUENCY"].data)
ds2.variables["FREQUENCY"].data[:] = 99.99

# This should be the original array, but instead it's all 99.99
print(ds.variables["FREQUENCY"].data)

# I would expect both of these to print False, but it prints True, False
print(np.shares_memory(ds.variables["FREQUENCY"].data, ds2.variables["FREQUENCY"].data))
print(np.shares_memory(ds.variables["AMPLITUDE"].data, ds2.variables["AMPLITUDE"].data))
```

### MVCE confirmation

- [x] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [x] Complete example — the example is self-contained, including all data and the text of any traceback.
- [x] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [x] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [x] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

```Python
import xarray as xr
import numpy as np

ds = xr.load_dataset("data_clean.nc")
ds2 = ds.copy(deep=True)

print(ds.variables["FREQUENCY"].data)
ds2.variables["FREQUENCY"].data[:] = 99.99

# This should be the original array, but instead it's all 99.99
print(ds.variables["FREQUENCY"].data)

# I would expect both of these to print False, but it prints True, False
print(np.shares_memory(ds.variables["FREQUENCY"].data, ds2.variables["FREQUENCY"].data))
print(np.shares_memory(ds.variables["AMPLITUDE"].data, ds2.variables["AMPLITUDE"].data))
```

### Environment

<details>

```
>>> xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.15 | packaged by conda-forge | (main, Sep 20 2024, 16:31:41) [Clang 17.0.6 ]
python-bits: 64
OS: Darwin
OS-release: 21.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: (None, 'UTF-8')
libhdf5: 1.14.3
libnetcdf: 4.9.2

xarray: 2024.9.0
pandas: 2.2.3
numpy: 2.1.1
scipy: 1.14.1
netCDF4: 1.7.1
pydap: None
h5netcdf: None
h5py: None
zarr: None
cftime: 1.6.4
nc_time_axis: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.9.2
cartopy: None
seaborn: None
numbagg: None
fsspec: 2024.9.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 75.1.0
pip: 24.2
conda: None
pytest: 8.3.3
mypy: None
IPython: None
sphinx: None
```
</details>

**Comment by kmuehlbauer** [comment] 2024-11-15 09:43
Dupe of #7463, most likely your `FREQUENCY` is also a Coordinate/IndexVariable.

**Closed by kmuehlbauer** 2024-11-15 09:43 UTC
Labels: bug, needs triage
