### ISSUE TITLE
module 'xarray' has no attribute 'Coordinates'

### ISSUE THREAD

**Issue by harshitha1201** [pydata/xarray#8050] opened 2023-08-06 17:19 UTC
### What happened?

I have made some documentation changes to the user-guide/terminology.rst file of xarray. When doing ``make html``. This is the error message that is appearing. This problem has occured in two different folders, but while using the same file and command. 

WARNING: [autosummary] failed to import xarray.Coordinates.
Possible hints:
* ImportError: 
* ModuleNotFoundError: No module named 'xarray.Coordinates'
* AttributeError: module 'xarray' has no attribute 'Coordinates'

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

</details>

**Comment by benbovy** [comment] 2023-08-06 19:05
`from xarray import Coordinates` should work on the main branch. 

Perhaps you are building the documentation locally using main but still with an older version of Xarray installed in your environment?

**Comment by harshitha1201** [comment] 2023-08-07 12:34
My main branch is up to date with origin-main. Do I need to still do this?

**Comment by benbovy** [comment] 2023-08-07 14:25
AFAIK the `make html` command builds the documentation but doesn't (re)installs xarray in your local Python environment, which is needed to execute the examples in the documentation, etc.

Make sure to follow [these steps](https://docs.xarray.dev/en/stable/contributing.html#requirements) before running `make html`.

**Comment by harshitha1201** [comment] 2023-08-08 06:01
I have done this, but when I run ``make html`` all the files in doc are not built. In the _build file of doc folder I could only see some files of doc getting built. Let's say there are 10 .rst files in doc folder, but after running ``make html`` only 2 or 3 files are built.

**Comment by benbovy** [comment] 2023-08-08 07:48
I'm afraid I cannot help you much further as I cannot reproduce it. Try running `make clean` before `make html`. You could also check the full logs of the last build on readthedocs (which runs successfully) to see if it helps: https://readthedocs.org/projects/xray/builds/21535646/

I'm going to close this issue as I don't see any bug on the xarray side, but feel free to re-open it or comment if the problem persists.

**Closed by benbovy** 2023-08-08 07:48 UTC
Labels: bug, needs triage
