### ISSUE TITLE
Dataset.to_netcdf netcdf4 bytes

### ISSUE THREAD

**Issue by gareth-j** [pydata/xarray#3372] opened 2019-10-03 16:14 UTC
I understand that the `Dataset.to_netcdf` function will return bytes if no `path` is passed but will use the scipy backend for NetCDF creation and only supports version 3. Has anyone found a way of getting a NetCDF version 4 file as bytes?

**Comment by shoyer** [comment] 2019-10-04 04:45
I agree this would be nice to have. In principle, this could be done with either netCDF4's diskless datasets (https://unidata.github.io/netcdf4-python/netCDF4/index.html#section15) or h5py/h5netcdf's support for Python file-like objects (http://docs.h5py.org/en/stable/high/file.html#python-file-like-objects).

**Comment by gareth-j** [comment] 2019-10-07 09:24
OK, I'll have a go at a PR for this

**Comment by kmuehlbauer** [comment] 2023-09-16 08:32
Dupe of #23.

**Closed by kmuehlbauer** 2023-09-16 08:32 UTC
Labels: topic-backends
