### ISSUE TITLE
groupby() fails with a stack trace when Dask 0.15.3 is used

### ISSUE THREAD

**Issue by JanisGailis** [pydata/xarray#1592] opened 2017-09-26 10:15 UTC
Hi xarray team!

Our unit tests broke when Dask got updated to 0.15.3, after a quick investigation it became clear that groupby operation on an xarray Dataset fails with this Dask version.

The following example:
```python
import xarray as xr
import numpy as np
import dask


def plus_one(da):
    return da + 1


print(xr.__version__)
print(dask.__version__)

ds = xr.Dataset({
    'first': (['time', 'lat', 'lon'], np.array([np.eye(4, 8), np.eye(4, 8)])),
    'second': (['time', 'lat', 'lon'], np.array([np.eye(4, 8), np.eye(4, 8)])),
    'lat': np.linspace(-67.5, 67.5, 4),
    'lon': np.linspace(-157.5, 157.5, 8),
    'time': np.array([1, 2])}).chunk(chunks={'lat': 2, 'lon': 4})

ds_new = ds.groupby('time').apply(plus_one)
```
Produces the following output when Dask 0.15.3 is used:
```
0.9.6
0.15.3
Traceback (most recent call last):
  File "/home/ccitbx/Development/dask_test/dask_test.py", line 20, in <module>
    ds_new = ds.groupby('time').apply(plus_one)
  File "/home/ccitbx/miniconda3/envs/cate-new-dask/lib/python3.6/site-packages/xarray/core/groupby.py", line 617, in apply
    return self._combine(applied)
  File "/home/ccitbx/miniconda3/envs/cate-new-dask/lib/python3.6/site-packages/xarray/core/groupby.py", line 621, in _combine
    applied_example, applied = peek_at(applied)
  File "/home/ccitbx/miniconda3/envs/cate-new-dask/lib/python3.6/site-packages/xarray/core/utils.py", line 114, in peek_at
    peek = next(gen)
  File "/home/ccitbx/miniconda3/envs/cate-new-dask/lib/python3.6/site-packages/xarray/core/groupby.py", line 616, in <genexpr>
    applied = (func(ds, **kwargs) for ds in self._iter_grouped())
  File "/home/ccitbx/miniconda3/envs/cate-new-dask/lib/python3.6/site-packages/xarray/core/groupby.py", line 298, in _iter_grouped
    yield self._obj.isel(**{self._group_dim: indices})
  File "/home/ccitbx/miniconda3/envs/cate-new-dask/lib/python3.6/site-packages/xarray/core/dataset.py", line 1143, in isel
    new_var = var.isel(**var_indexers)
  File "/home/ccitbx/miniconda3/envs/cate-new-dask/lib/python3.6/site-packages/xarray/core/variable.py", line 570, in isel
    return self[tuple(key)]
  File "/home/ccitbx/miniconda3/envs/cate-new-dask/lib/python3.6/site-packages/xarray/core/variable.py", line 400, in __getitem__
    values = self._indexable_data[key]
  File "/home/ccitbx/miniconda3/envs/cate-new-dask/lib/python3.6/site-packages/xarray/core/indexing.py", line 498, in __getitem__
    value = self.array[key]
  File "/home/ccitbx/miniconda3/envs/cate-new-dask/lib/python3.6/site-packages/dask/array/core.py", line 1222, in __getitem__
    index2 = normalize_index(index, self.shape)
  File "/home/ccitbx/miniconda3/envs/cate-new-dask/lib/python3.6/site-packages/dask/array/slicing.py", line 762, in normalize_index
    raise IndexError("Too many indices for array")
IndexError: Too many indices for array
```
It works as expected when Dask < 0.15.3 is used.

I don't have enough understanding regarding what's really going on in Dask-land, so I leave it to you guys to open an issue in their Issue tracker if needed!

**Comment by fujiisoup** [comment] 2017-09-26 10:52
It looks a duplicate of #1591.
This bug is issued in the upstream.

**Comment by JanisGailis** [comment] 2017-09-26 11:52
Yes, must be the same issue. Thanks for fixing it! Feel free to close this as a duplicate.

**Closed** 2017-10-04 21:42 UTC
