### ISSUE TITLE
Broadcast error when dataset is recombined after a stack/groupby/apply/unstack sequence

### ISSUE THREAD

**Issue by monocongo** [pydata/xarray#873] opened 2016-06-07 15:50 UTC
I have code which performs the split-apply-combine pattern on a dataset, and it appears to work as expected until it reaches a point where the dataset is being recombined. At this point it seems that there's a dimensional mismatch between arrays which is causing numpy to raise a broadcasting error (below).

The code which can cause this error is in a gist [here](https://gist.github.com/monocongo/233abf7bcf423d6d628f9379663d3ca2)

When I run the code I see the following errors/traceback:

```
Traceback (most recent call last):
  File "H:\git\climate_indices\src\scripts\xarray_groupby_example.py", line 34, in <module>
    dataset = dataset.groupby('grid_cells').apply(double_data)
  File "C:\Anaconda\lib\site-packages\xarray\core\groupby.py", line 469, in apply
    combined = self._concat(applied)
  File "C:\Anaconda\lib\site-packages\xarray\core\groupby.py", line 476, in _concat
    combined = concat(applied, concat_dim, positions=positions)
  File "C:\Anaconda\lib\site-packages\xarray\core\combine.py", line 114, in concat
    return f(objs, dim, data_vars, coords, compat, positions)
  File "C:\Anaconda\lib\site-packages\xarray\core\combine.py", line 268, in _dataset_concat
    combined = Variable.concat(vars, dim, positions)
  File "C:\Anaconda\lib\site-packages\xarray\core\variable.py", line 919, in concat
    variables = list(variables)
  File "C:\Anaconda\lib\site-packages\xarray\core\combine.py", line 262, in ensure_common_dims
    var = var.expand_dims(common_dims, common_shape)
  File "C:\Anaconda\lib\site-packages\xarray\core\variable.py", line 717, in expand_dims
    expanded_data = ops.broadcast_to(self.data, tmp_shape)
  File "C:\Anaconda\lib\site-packages\xarray\core\ops.py", line 67, in f
    return getattr(module, name)(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\numpy\lib\stride_tricks.py", line 115, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "C:\Anaconda\lib\site-packages\numpy\lib\stride_tricks.py", line 70, in _broadcast_to
    op_flags=[op_flag], itershape=shape, order='C').itviews[0]
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,) and requested shape (1,)

```

I get the above error when I use NetCDF input files which contain three dimensions (time, lon, lat), a simple example of which is described below:

```
Dataset type: Hierarchical Data Format, version 5
 
netcdf file:/C:/home/tmp/toy.nc {

  dimensions:
    lat = 2;
    lon = 2;
    time = 3;

  variables:
    int prcp(time=3, lon=2, lat=2);
    double lat(lat=2);
    double lon(lon=2);
    long time(time=3);
      :calendar = "proleptic_gregorian";
      :units = "days since 2014-06-09 00:00:00";
}
```

**Comment by shoyer** [comment] 2016-06-08 04:34
Thanks for raising this one on GitHub (after I forgot to respond on the mailing list!). I have a partial fix for this in https://github.com/pydata/xarray/pull/867, but we clearly need some more tests to verify that groupby with a multi-index works properly.

**Comment by shoyer** [comment] 2016-07-29 04:38
Fixed by #867

**Comment by monocongo** [comment] 2016-08-22 20:32
I get the following error now when I try to run the gist code referenced in the original message above: 

```
$ python -u xarray_gist.py /dev/shm/nclimgrid_prcp_reduced.nc nclimgrid_prcp_doubled.nc
Traceback (most recent call last):
  File "xarray_gist.py", line 45, in <module>
    encoding = {variable_name: {'_FillValue': np.nan, 'dtype': 'float32'}})
  File "/home/james.adams/anaconda3/lib/python3.5/site-packages/xarray/core/dataset.py", line 782, in to_netcdf
    engine=engine, encoding=encoding)
  File "/home/james.adams/anaconda3/lib/python3.5/site-packages/xarray/backends/api.py", line 354, in to_netcdf
    dataset.dump_to_store(store, sync=sync, encoding=encoding)
  File "/home/james.adams/anaconda3/lib/python3.5/site-packages/xarray/core/dataset.py", line 728, in dump_to_store
    store.store(variables, attrs, check_encoding)
  File "/home/james.adams/anaconda3/lib/python3.5/site-packages/xarray/backends/common.py", line 234, in store
    check_encoding_set)
  File "/home/james.adams/anaconda3/lib/python3.5/site-packages/xarray/backends/common.py", line 209, in store
    self.set_variables(variables, check_encoding_set)
  File "/home/james.adams/anaconda3/lib/python3.5/site-packages/xarray/backends/common.py", line 219, in set_variables
    target, source = self.prepare_variable(name, v, check)
  File "/home/james.adams/anaconda3/lib/python3.5/site-packages/xarray/backends/netCDF4_.py", line 266, in prepare_variable
    raise_on_invalid=check_encoding)
  File "/home/james.adams/anaconda3/lib/python3.5/site-packages/xarray/backends/netCDF4_.py", line 167, in _extract_nc4_encoding
    ' %r' % (backend, invalid))
ValueError: unexpected encoding parameters for 'netCDF4' backend:  ['dtype']

```

Additionally I see the following errors when I run some other code which uses the same dataset.groupby().apply() technique (the trouble appears to show up within numpy.convolve()):

```
 Traceback (most recent call last):
  File "C:\home\git\indices\src\main\python\indices\spi_gamma_xarray.py", line 46, in <module>
    dataset = dataset.groupby('grid_cells').apply(function_to_be_applied)
  File "C:\Anaconda3\lib\site-packages\xarray\core\groupby.py", line 567, in apply
    combined = self._concat(applied)
  File "C:\Anaconda3\lib\site-packages\xarray\core\groupby.py", line 572, in _concat
    applied_example, applied = peek_at(applied)
  File "C:\Anaconda3\lib\site-packages\xarray\core\utils.py", line 90, in peek_at
    peek = next(gen)
  File "C:\Anaconda3\lib\site-packages\xarray\core\groupby.py", line 566, in <genexpr>
    applied = (func(ds, **kwargs) for ds in self._iter_grouped())
  File "C:\home\git\indices\src\main\python\indices\spi_gamma_xarray.py", line 27, in function_to_be_applied
    valid_max)
  File "C:\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 1005, in convolve
    return multiarray.correlate(a, v[::-1], mode)
TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'
Traceback (most recent call last):
  File "C:\home\git\indices\src\main\python\indices\spi_gamma_xarray.py", line 46, in <module>
    dataset = dataset.groupby('grid_cells').apply(function_to_be_applied)
  File "C:\Anaconda3\lib\site-packages\xarray\core\groupby.py", line 567, in apply
    combined = self._concat(applied)
  File "C:\Anaconda3\lib\site-packages\xarray\core\groupby.py", line 572, in _concat
    applied_example, applied = peek_at(applied)
  File "C:\Anaconda3\lib\site-packages\xarray\core\utils.py", line 90, in peek_at
    peek = next(gen)
  File "C:\Anaconda3\lib\site-packages\xarray\core\groupby.py", line 566, in <genexpr>
    applied = (func(ds, **kwargs) for ds in self._iter_grouped())
  File "C:\home\git\indices\src\main\python\indices\spi_gamma_xarray.py", line 27, in function_to_be_applied
    valid_max)
  File "C:\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 1005, in convolve
    return multiarray.correlate(a, v[::-1], mode)
TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'
```


Please advise if I can provide any further information which might help work this out, or if I have made wrong assumptions as to how this feature should be used. Thanks.

**Comment by shoyer** [comment] 2016-08-23 04:42
Could you please share a data file and/or code which I can run to reproduce each of these issues?

**Comment by monocongo** [comment] 2016-08-25 20:48
Thanks, Stephan. In general things appear to be working much more as
expected now, probably (hopefully) this is just an edge case/nuance that
won't be too difficult for you guys to address. If so and if I don't run
across any other issues then my code will be dramatically simplified by
leveraging xarray rather than writing code to enable shared memory objects
for the multiprocessing side of things (my assumption being that you guys
have done a better job of that than I can).

A gist with example code and a smallish data file attached to the comment
is here: https://gist.github.com/monocongo/e8e883c2355f7a92bb0b9d24db5407a8

Please let me know if I can do anything else to help you help me. Godspeed!

--James

**Comment by shoyer** [comment] 2016-08-28 01:37
The second issue is that `compute_function` is being called on an `xarray.Dataset`, so `np.convolve(data, data * 2)` is attempting to convolve two xarray Datasets. NumPy gives a pretty unhelpful error message. (If only we had static typing in Python...)

**Comment by shoyer** [comment] 2016-08-28 01:53
The first issue is an xarray bug. See #989 for a fix.

The work around is not to provide an encoded dtype if the variable already has the dtype you want.

**Comment by monocongo** [comment] 2016-09-20 06:42
Thanks, Stephan. My code uses numpy.convolve() in several key places, so if that function is a deal breaker for using xarray then I'll hold off until that's fixed. In the meantime if there's anything else I can do to help you work this out then please let me know.

**Comment by shoyer** [comment] 2016-09-20 15:54
GroupBy is working as intended here. `ds.groupby('something').apply(func)` calls `func` on objects of the same type as `ds`. If you group a `Dataset`, each time you apply to a `Dataset`, too.

You can certainly still use `np.convolve`, but you'll need to manually apply it to numpy arrays extracted from a Dataset and then rebuild another Dataset or DataArray.

**Comment by monocongo** [comment] 2016-09-20 19:37
Thanks for this clarification, Stephan. Apparently I didn't read the API
documentation closely enough, as I was assuming that the function is
applied to the underlying ndarray rather than to all data variables of a
Dataset object. Now that I've taken the approach you suggested I'm cooking
with gas, and it's very encouraging. I really appreciate your help.

​--James
​

**Comment by shoyer** [comment] 2016-09-20 19:55
Great, glad that worked!

**Closed by shoyer** 2016-09-20 19:55 UTC
