### ISSUE TITLE
Unable to convert times to datetime when first and last value are masked

### ISSUE THREAD

**Issue by skorper** [pydata/xarray#7210] opened 2022-10-25 01:57 UTC
### What happened?

In the following conditions, I am unable to open a NetCDF file in xarray with `mask_and_scale=True` and `decode_times=True`:

* Unusual timestamp format in `time` variable `units` attr, e.g. `seconds since 2000-1-1 0:0:0 0`
* First and last value in `time` matches `_FillValue`

The following changes to the NetCDF file allows me to open the file in xarray:

* Update timestamp format in `units` attr to something more common (e.g. `seconds since 2000-01-01T00:00:00`)

OR

* Update first and last value in `time` variable to value that is not equal to `_FillValue`

### What did you expect to happen?

I should be able to open the NetCDF file with `mask_and_scale=True` and `decode_times=True` without errors.

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import numpy as np

fill_val = -99999.0
time_vals = np.random.rand(10)
time_vals[0] = fill_val
time_vals[-1] = fill_val

data_vars = {
    'foo': (['x'], np.random.rand(10)),
    'time': (
        ['x'],
        time_vals,
        {
            'units': 'seconds since 2000-1-1 0:0:0 0',
            '_FillValue': fill_val,
            'standard_name': 'time',
            'calendar': 'standard'
        }
    ),
}

ds = xr.Dataset(
    data_vars=data_vars,
    coords={'x': (['x'], np.arange(10))}
)

nc_out_location = '/path/to/example.nc'
ds.to_netcdf(nc_out_location)
ds = xr.open_dataset(nc_out_location)  # This line results in an error
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
dateutil.parser._parser.ParserError: Unknown string format: 2000-1-1 0:0:0 0
...
ValueError: could not convert string to Timestamp
...
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime
...
TypeError: unsupported operand type(s) for +: 'cftime._cftime.DatetimeGregorian' and 'NoneType'
...
ValueError: unable to decode time units 'seconds since 2000-1-1 0:0:0 0' with "calendar 'standard'". Try opening your dataset with decode_times=False or installing cftime if it is not installed.
```

### Anything else we need to know?

Looking at the code, it seems like this is happening because `_decode_cf_datetime_dtype` in times.py is only selecting the first and last values from the data, which in this case are masked due to _FillValue. 

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.1 (default, Jan  8 2021, 17:17:17) 
[Clang 12.0.0 (clang-1200.0.32.28)]
python-bits: 64
OS: Darwin
OS-release: 21.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.0
libnetcdf: 4.7.4

xarray: 2022.10.0
pandas: 1.4.1
numpy: 1.22.3
scipy: 1.8.0
netCDF4: 1.5.7
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.5.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: None
iris: None
bottleneck: None
dask: 2022.02.0
distributed: 2022.02.0
matplotlib: 3.5.1
cartopy: None
seaborn: None
numbagg: None
fsspec: 2022.01.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 60.10.0
pip: 21.1.1
conda: None
pytest: None
IPython: None
sphinx: None

</details>

**Comment by skorper** [comment] 2022-10-25 18:41
After further investigation, this issue seems to arise if any if the values in the `time` variable are masked, not just the first and last values. 

It looks like `cftime` doesn't support nans, which is why this error is occuring.

**Comment by kmuehlbauer** [comment] 2024-11-04 11:27
Not sure how much has been fixed in the cf decoding since creation of that issue. But as of today I think the root cause is that pd.Timestamp can't convert the reference time with the broken tz element:

```python
import pandas as pd
pd.Timestamp('2000-1-1 0:0:0 0')
# ---------------------------------------------------------------------------
# DateParseError                            Traceback (most recent call last)
# Cell In[28], line 2
#       1 import pandas as pd
# ----> 2 pd.Timestamp('2000-1-1 0:0:0 0')
# File timestamps.pyx:1865, in pandas._libs.tslibs.timestamps.Timestamp.__new__()
# File conversion.pyx:364, in pandas._libs.tslibs.conversion.convert_to_tsobject()
# File conversion.pyx:641, in pandas._libs.tslibs.conversion.convert_str_to_tsobject()
# File parsing.pyx:336, in pandas._libs.tslibs.parsing.parse_datetime_string()
# File parsing.pyx:666, in pandas._libs.tslibs.parsing.dateutil_parse()
# DateParseError: Unknown datetime string format, unable to parse: 2000-1-1 0:0:0 0
```

@skorper Your example works nicely, when fixing the time unit, as you already suggested (like
'seconds since 2000-01-01 00:00:00 0:0'), even if there are masked values.

So for an automated workflow with existing data, one would read open the file with `decode_times=False`, fix the unit and run `xr.decode_cf()` on the dataset.

Should this be closed as upstream issue?

**Comment by dcherian** [comment] 2024-11-04 20:17
yeah the error message is nice and clear. let's close

**Closed by dcherian** 2024-11-04 20:17 UTC
Labels: bug, upstream issue, topic-cftime
