### ISSUE TITLE
df.polyfit() does not work as expected

### ISSUE THREAD

**Issue by TheJeran** [pydata/xarray#7930] opened 2023-06-20 10:32 UTC
### What happened?

I am working with a spatiotemporal dataset and would like to get the slope of the temporal data over the given period. This should simply be

```
fit = df.polyfit(dim='var',deg=1)
fit['polyfit_coefficients'][0]
```

However I get values that are basically zero (~e-15)

Here is some code to visualize what I'm talking about

```
ds = xr.tutorial.load_dataset('air_temperature')

# Compute polynomial fit
fit = ds.air.sel(time=slice('2013-1-1','2013-1-31')).polyfit(dim='time', deg=1)

fit['polyfit_coefficients'][0].plot()
```
![image](https://github.com/pydata/xarray/assets/76405582/ed87a23a-40ff-4cfd-bcc1-5c3730af00e8)

```
#plot the time series of a pixel from the dataset
sub_df = ds.air.sel(time=slice('2013-1-1','2013-1-31')).sel(lon=245,lat=58,method='nearest')
sub_df.plot(label='TS')

#get coefficients at that pixel
slope,intercept = fit['polyfit_coefficients'].sel(lon=245,lat=58,method='nearest').values

#plot that line
y = [i*slope+intercept for i in range(len(sub_df.time))]
plt.plot(sub_df.time,y,label="Line")
plt.legend()
plt.plot()
```
![image](https://github.com/pydata/xarray/assets/76405582/0a35c5ed-b3a3-49fa-9af0-3c3e723821e8)

Here's how it should look

```
#plot the time series of a pixel from the dataset
sub_df = ds.air.sel(time=slice('2013-1-1','2013-1-31')).sel(lon=245,lat=58,method='nearest')
sub_df.plot(label='TS')

#get coefficients at that pixel
slope,intercept = np.polyfit(x=range(len(sub_df.time)),y=sub_df.values,deg=1)

#plot that line against the time series
y = [i*slope+intercept for i in range(len(sub_df.time))]
plt.plot(sub_df.time,y,label="Line")
plt.legend()
plt.plot()
```

![image](https://github.com/pydata/xarray/assets/76405582/c47f2129-3d22-4a3a-b87b-34c74ac5e194)

### What did you expect to happen?

Here's how it should look

```
#plot the time series of a pixel from the dataset
sub_df = ds.air.sel(time=slice('2013-1-1','2013-1-31')).sel(lon=245,lat=58,method='nearest')
sub_df.plot(label='TS')

#get coefficients at that pixel
slope,intercept = np.polyfit(x=range(len(sub_df.time)),y=sub_df.values,deg=1)

#plot that line against the time series
y = [i*slope+intercept for i in range(len(sub_df.time))]
plt.plot(sub_df.time,y,label="Line")
plt.legend()
plt.plot()
```

![image](https://github.com/pydata/xarray/assets/76405582/c47f2129-3d22-4a3a-b87b-34c74ac5e194)

### Minimal Complete Verifiable Example

```Python
ds = xr.tutorial.load_dataset('air_temperature')

# Compute polynomial fit
fit = ds.air.sel(time=slice('2013-1-1','2013-1-31')).polyfit(dim='time', deg=1)

fit['polyfit_coefficients'][0].plot()

#plot the time series of a pixel from the dataset
sub_df = ds.air.sel(time=slice('2013-1-1','2013-1-31')).sel(lon=245,lat=58,method='nearest')
sub_df.plot(label='TS')

#get coefficients at that pixel
slope,intercept = fit['polyfit_coefficients'].sel(lon=245,lat=58,method='nearest').values

#plot that line
y = [i*slope+intercept for i in range(len(sub_df.time))]
plt.plot(sub_df.time,y,label="Line")
plt.legend()
plt.plot()
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.9.12 (main, Jun  1 2022, 11:38:51) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 4.15.0-167-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: C.UTF-8
LANG: None
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.10.6
libnetcdf: 4.8.1

xarray: 2022.3.0
pandas: 1.4.3
numpy: 1.22.3
scipy: 1.7.3
netCDF4: 1.5.7
pydap: None
h5netcdf: 1.0.2
h5py: 2.10.0
Nio: None
zarr: 2.8.1
cftime: 1.5.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: None
iris: None
bottleneck: 1.3.5
dask: 2022.7.0
distributed: 2022.7.0
matplotlib: 3.5.2
cartopy: 0.21.1
seaborn: 0.12.2
numbagg: None
fsspec: 2022.3.0
cupy: None
pint: None
sparse: None
setuptools: 61.2.0
pip: 22.1.2
conda: None
pytest: None
IPython: 8.4.0
sphinx: None

</details>

**Comment by kmuehlbauer** [comment] 2023-06-20 13:41
@TheJeran The issue is with the coordinates, you would need to cast the times to float64 to make this work. Or you just stay in xarray-land and use `xr.polyval` to calculate the fit values.

```python
ds = xr.tutorial.load_dataset('air_temperature').air.sel(time=slice('2013-1-1','2013-1-31'))

# Compute polynomial fit
fit = ds.polyfit(dim='time', deg=1)

# plot the time series of a pixel from the dataset
sub_df = ds.sel(lon=245,lat=58,method='nearest')

# get coefficients at that pixel
slope, intercept = fit['polyfit_coefficients'].sel(lon=245,lat=58,method='nearest').values
# or calculate fit values using xr.polyval
fitval = xr.polyval(coord=ds.time, coeffs=fit["polyfit_coefficients"])

fig = plt.figure()
ax1 = fig.add_subplot(211)
ax2 = fig.add_subplot(212)

# plot that line
# here astype np.float is needed
y = [i*slope+intercept for i in sub_df.time.values.astype(np.float64)]
sub_df.plot(label='TS', ax=ax1)
ax1.plot(sub_df.time, y, label="Line1")
ax1.set_title("by slope")
# or second variant using xr.polyval
sub_df.plot(label='TS', ax=ax2)
fitval.sel(lon=245,lat=58, method='nearest').plot(x="time", ax=ax2, label="Line2")
ax2.set_title("by xr.polyval")
fig.tight_layout()
```
![polyfit](https://github.com/pydata/xarray/assets/5821660/34558560-ed06-45ae-820e-eabc34610a98)

**Comment by kmuehlbauer** [comment] 2023-06-28 05:13
@TheJeran I'm closing this now. Please reopen, if something is unclear.

**Closed by kmuehlbauer** 2023-06-28 05:13 UTC
Labels: usage question
