### ISSUE TITLE
xarray fails on Travis CI

### ISSUE THREAD

**Issue by pnsaevik** [pydata/xarray#5566] opened 2021-07-02 13:28 UTC
Hi,

I have a project build on xarray that now fails on travis. It only fails on python 3.7. Have no idea why.

Minimal sample travis.yml that still fails:

--------------------
language: python
python:
- "3.7"

install:
  - python --version
  - pip --version
  - pip install --upgrade setuptools numpy
  - pip install xarray
  - pip list

script:
  - python -c "import xarray"
-----------------------------

Error message (stack trace):

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/xarray/__init__.py", line 3, in <module>
    from . import testing, tutorial, ufuncs
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/xarray/testing.py", line 8, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/xarray/core/duck_array_ops.py", line 16, in <module>
    from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/xarray/core/npcompat.py", line 81, in <module>
    from numpy.typing import ArrayLike, DTypeLike
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/numpy/typing/__init__.py", line 315, in <module>
    from ._shape import _Shape, _ShapeLike
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/numpy/typing/_shape.py", line 15, in <module>
    _ShapeLike = Union[SupportsIndex, Sequence[SupportsIndex]]
  File "/opt/python/3.7.1/lib/python3.7/typing.py", line 251, in inner
    return func(*args, **kwds)
  File "/opt/python/3.7.1/lib/python3.7/typing.py", line 626, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/opt/python/3.7.1/lib/python3.7/typing.py", line 626, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/opt/python/3.7.1/lib/python3.7/typing.py", line 139, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got NotImplemented.
The command "python -c "import xarray"" exited with 1.

**Comment by max-sixty** [comment] 2021-07-02 15:52
Could you run the command to list all versions as per the issue template?

**Comment by pnsaevik** [comment] 2021-07-02 19:16
I can't import xarray, so I can't run the command. But "pip list" returns the following:

atomicwrites       1.3.0
attrs              19.1.0
certifi            2019.3.9
importlib-metadata 0.18
mock               4.0.2
more-itertools     7.0.0
nose               1.3.7
numpy              1.21.0
packaging          19.0
pandas             1.3.0
pip                20.1.1
pipenv             2018.11.26
pluggy             0.12.0
py                 1.8.0
pyparsing          2.4.0
pytest             5.4.3
python-dateutil    2.8.1
pytz               2021.1
setuptools         57.0.0
six                1.12.0
virtualenv         16.6.0
virtualenv-clone   0.5.3
wcwidth            0.1.7
wheel              0.34.2
xarray             0.17.0
zipp               0.5.1

**Comment by dcherian** [comment] 2021-07-02 19:21
This is a duplicate of https://github.com/pydata/xarray/issues/5513 and seems to be fixed upstream in numpy. So I'm closing this issue.

**Closed by dcherian** 2021-07-02 19:21 UTC

**Comment by pnsaevik** [comment] 2021-07-02 19:23
Thanks!
