### ISSUE TITLE
Crash with tensorflow when using "to_netcdf"

### ISSUE THREAD

**Issue by sjh11556** [pydata/xarray#3828] opened 2020-03-04 07:27 UTC
When tensorflow is imported, to_netcdf does not work.

```python
import tensorflow as tf
import xarray as xr
import numpy as np

data=xr.DataArray(data=np.zeros([4,5]),dims=['lat','lon'])
data.to_netcdf("tmp.nc")
```

throws an error message
```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/cdat81/lib/python3.7/site-packages/xarray/backends/api.py", line 1089, in to_netcdf
    dataset, store, writer, encoding=encoding, unlimited_dims=unlimited_dims
  File "/usr/local/anaconda3/envs/cdat81/lib/python3.7/site-packages/xarray/backends/api.py", line 1135, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/usr/local/anaconda3/envs/cdat81/lib/python3.7/site-packages/xarray/backends/common.py", line 298, in store
    variables, check_encoding_set, writer, unlimited_dims=unlimited_dims
  File "/usr/local/anaconda3/envs/cdat81/lib/python3.7/site-packages/xarray/backends/common.py", line 339, in set_variables
    writer.add(source, target)
  File "/usr/local/anaconda3/envs/cdat81/lib/python3.7/site-packages/xarray/backends/common.py", line 188, in add
    target[...] = source
  File "/usr/local/anaconda3/envs/cdat81/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 51, in __setitem__
    data[key] = value
  File "netCDF4/_netCDF4.pyx", line 4950, in netCDF4._netCDF4.Variable.__setitem__
  File "netCDF4/_netCDF4.pyx", line 5229, in netCDF4._netCDF4.Variable._put
  File "netCDF4/_netCDF4.pyx", line 1887, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: HDF error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/cdat81/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-17ffeb3a8c2a>", line 1, in <module>
    runfile('/home/jihoons/program/deepCLOUD/CMIP/2_predict/test.py', wdir='/home/jihoons/program/deepCLOUD/CMIP/2_predict')
  File "/home/jihoons/pycharm-2019.1.1/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/jihoons/pycharm-2019.1.1/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jihoons/program/deepCLOUD/CMIP/2_predict/test.py", line 7, in <module>
    data.to_netcdf("tmp.nc")
  File "/usr/local/anaconda3/envs/cdat81/lib/python3.7/site-packages/xarray/core/dataarray.py", line 2353, in to_netcdf
    return dataset.to_netcdf(*args, **kwargs)
  File "/usr/local/anaconda3/envs/cdat81/lib/python3.7/site-packages/xarray/core/dataset.py", line 1545, in to_netcdf
    invalid_netcdf=invalid_netcdf,
  File "/usr/local/anaconda3/envs/cdat81/lib/python3.7/site-packages/xarray/backends/api.py", line 1104, in to_netcdf
    store.close()
  File "/usr/local/anaconda3/envs/cdat81/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 492, in close
    self._manager.close(**kwargs)
  File "/usr/local/anaconda3/envs/cdat81/lib/python3.7/site-packages/xarray/backends/file_manager.py", line 221, in close
    file.close()
  File "netCDF4/_netCDF4.pyx", line 2485, in netCDF4._netCDF4.Dataset.close
  File "netCDF4/_netCDF4.pyx", line 2449, in netCDF4._netCDF4.Dataset._close
  File "netCDF4/_netCDF4.pyx", line 1887, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: HDF error
```

The code works fine when tensorflow is not imported. It seems like xarray uses wrong netcdf library when tensorflow is imported.

tensorflow => 2.1.0
xarray        => 0.15.0

**Comment by max-sixty** [comment] 2020-03-04 11:35
Hi @sjh11556 — I can't reproduce that locally. What makes you think xarray is using the wrong netcdf library?

Could you fill out the standard issue template and list your dependencies? Thanks

**Comment by max-sixty** [comment] 2020-03-22 20:45
Closing but reopen with issue template if still an issue, cheers

**Closed by max-sixty** 2020-03-22 20:45 UTC
