### ISSUE TITLE
Dataset to zarr not working with newest s3fs Storage (s3fs > 0.5.0)

### ISSUE THREAD

**Issue by jhnnsrs** [pydata/xarray#4478] opened 2020-10-01 12:11 UTC
**What happened**:
A call to zarr storage to mino instance fails with newest s3fs storage (s3fs > 0.5.0) while perfectly working with s3fs == 0.4.0. Might be due to s3fs' reliance on aiobotocore as Traceback.
```
Traceback (most recent call last):
Exception in callback <TaskStepMethWrapper object at 0x7fbe34300350>()
handle: <Handle <TaskStepMethWrapper object at 0x7fbe34300350>()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Leaving task <Task finished coro=<sync.<locals>.f() done, defined at /usr/local/lib/python3.7/site-packages/fsspec/asyn.py:43> result=None> does not match the current task None.
  File "test_without.py", line 27, in <module>
    array.to_dataset().to_zarr(store=s3store, mode="w", consolidated=True, compute=True)
  File "/usr/local/lib/python3.7/site-packages/xarray/core/dataset.py", line 1662, in to_zarr
    append_dim=append_dim,
  File "/usr/local/lib/python3.7/site-packages/xarray/backends/api.py", line 1369, in to_zarr
    writes = writer.sync(compute=compute)
  File "/usr/local/lib/python3.7/site-packages/xarray/backends/common.py", line 161, in sync
    regions=self.regions,
  File "/usr/local/lib/python3.7/site-packages/dask/array/core.py", line 981, in store
    result.compute(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dask/base.py", line 452, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/usr/local/lib/python3.7/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/usr/local/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/usr/local/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/usr/local/lib/python3.7/site-packages/dask/array/core.py", line 3722, in store_chunk
    return load_store_chunk(x, out, index, lock, return_stored, False)
  File "/usr/local/lib/python3.7/site-packages/dask/array/core.py", line 3711, in load_store_chunk
    out[index] = np.asanyarray(x)
  File "/usr/local/lib/python3.7/site-packages/zarr/core.py", line 1115, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/usr/local/lib/python3.7/site-packages/zarr/core.py", line 1210, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/usr/local/lib/python3.7/site-packages/zarr/core.py", line 1501, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/usr/local/lib/python3.7/site-packages/zarr/core.py", line 1550, in _set_selection
    self._chunk_setitem(chunk_coords, chunk_selection, chunk_value, fields=fields)
  File "/usr/local/lib/python3.7/site-packages/zarr/core.py", line 1665, in _chunk_setitem
    fields=fields)
  File "/usr/local/lib/python3.7/site-packages/zarr/core.py", line 1729, in _chunk_setitem_nosync
    self.chunk_store[ckey] = cdata
  File "/usr/local/lib/python3.7/site-packages/fsspec/mapping.py", line 150, in __setitem__
    self.fs.mkdirs(self.fs._parent(key), exist_ok=True)
  File "/usr/local/lib/python3.7/site-packages/fsspec/spec.py", line 1066, in mkdirs
    return self.makedirs(path, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/site-packages/s3fs/core.py", line 488, in makedirs
    self.mkdir(path, create_parents=True)
  File "/usr/local/lib/python3.7/site-packages/fsspec/asyn.py", line 118, in wrapper
    return maybe_sync(func, self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fsspec/asyn.py", line 97, in maybe_sync
    return sync(loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fsspec/asyn.py", line 68, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/fsspec/asyn.py", line 52, in f
    result[0] = await future
  File "/usr/local/lib/python3.7/site-packages/s3fs/core.py", line 462, in _mkdir
    if not key or (create_parents and not self.exists(bucket)):
  File "/usr/local/lib/python3.7/site-packages/fsspec/asyn.py", line 118, in wrapper
    return maybe_sync(func, self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fsspec/asyn.py", line 90, in maybe_sync
    return _run_until_done(func(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/fsspec/asyn.py", line 28, in _run_until_done
    loop._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
    handle = self._ready.popleft()
IndexError: pop from an empty deque
```
**What you expected to happen**:

Storage succeeding. No Exception.

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
import dask.array as da
import xarray
import s3fs
import xarray as xr

bucket = "zarr"
name = "sample"

nana = xarray.DataArray(da.zeros((1023,1023,3)))

s3_path = f"{bucket}/{name}"
s3 = s3fs.S3FileSystem(client_kwargs={"endpoint_url": "s3://minio:9000"}, username="weak_access_key", password="weak_secret_key")
s3store = s3.get_mapper(s3_path)


print("Storing")
nana.to_dataset().to_zarr(store=s3store, mode="w", consolidated=True, compute=True)
print("Getting")
```

**Anything else we need to know?**:

Thanks and keep up the great work!

**Environment**:

dask==2.28.0
xarray==0.16.1
aiobotocore==1.1.1
fsspec==0.8.3
zarr==2.4.0
s3fs==0.5.1

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.8 (default, Jun 30 2020, 18:27:23) 
[GCC 8.3.0]
python-bits: 64
OS: Linux
OS-release: 4.19.104-microsoft-standard
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: None
libnetcdf: None

xarray: 0.16.1
pandas: 1.1.2
numpy: 1.19.2
scipy: 1.5.2
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: 2.4.0
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.28.0
distributed: 2.28.0
matplotlib: 3.3.2
cartopy: None
seaborn: 0.11.0
numbagg: None
pint: None
setuptools: 47.3.1
pip: 20.1.1
conda: None
pytest: 6.1.0
IPython: 7.18.1
sphinx: None

</details>

**Comment by rabernat** [comment] 2020-10-01 13:00
Thanks for the bug report! There were recently some big changes to s3fs. We will look into it.

cc @martindurant

**Comment by martindurant** [comment] 2020-10-01 13:11
The following code, modified to the style of the s3fs test suite, works OK:
```python
def test_with_xzarr(s3):
    da = pytest.importorskip("dask.array")
    xr = pytest.importorskip("xarray")
    name = "sample"

    nana = xr.DataArray(da.zeros((1023, 1023, 3)))

    s3_path = f"{test_bucket_name}/{name}"
    s3store = s3.get_mapper(s3_path)

    print("Storing")
    nana.to_dataset().to_zarr(store=s3store, mode="w", consolidated=True, compute=True)
```

**Comment by martindurant** [comment] 2020-10-01 15:27
```
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
    handle = self._ready.popleft()
```

This looks like it may be a race conditions where multiple threads are calling the event loop at once. I wonder if you could list the event loops in use and the threads (perhaps best run with base python than ipython/jupyter).

**Comment by rabernat** [comment] 2020-10-01 16:38
Martin, thanks for your comments. I have read them several times but am left scratching my head as to their meaning. It would be useful if you could help identify a specific development direction to address @jhnnsrs's bug. In your best judgement, is this
- a bug in xarray
- a bug in dask
- a bug in zarr
- a bug in s3fs
- some problem relating to @jhnnsrs's environment / dependencies
- something else?

**Comment by jhnnsrs** [comment] 2020-10-02 09:51
Thanks for the troubleshooting.  I encountered the problem within an sync worker in django channels (has been and is still working with s3fs=0.4.1 ) (same error).  So I tried running the refactored relevant code in a _vanilla_ python script on a linux docker container with WSL2 backend, no event loops and no threads running. Same results and the reason I posted in in xarray issues.

No coming back to this problem a day the vanilla script works perfectly sound and gets the job down! The Django sync worker example still runs into problems:

```
[ERROR]  asyncio 2020-10-02 09:40:10,950 :: Exception in callback BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))
handle: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 510, in _sock_connect_cb
    fut.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
[ERROR]  asyncio 2020-10-02 09:40:11,609 :: Exception in callback BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))
handle: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 510, in _sock_connect_cb
    fut.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
[ERROR]  asyncio 2020-10-02 09:40:12,478 :: Exception in callback BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))
handle: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 510, in _sock_connect_cb
    fut.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
[ERROR]  asyncio 2020-10-02 09:40:12,743 :: Exception in callback BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))
handle: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 510, in _sock_connect_cb
    fut.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
[ERROR]  asyncio 2020-10-02 09:40:12,745 :: Exception in callback BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))
handle: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 510, in _sock_connect_cb
    fut.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
[ERROR]  asyncio 2020-10-02 09:40:12,757 :: Exception in callback BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))
handle: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 510, in _sock_connect_cb
    fut.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
[ERROR]  asyncio 2020-10-02 09:40:13,631 :: Exception in callback BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))
handle: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 510, in _sock_connect_cb
    fut.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
[ERROR]  asyncio 2020-10-02 09:40:13,633 :: Exception in callback BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))
handle: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 510, in _sock_connect_cb
    fut.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
[ERROR]  asyncio 2020-10-02 09:40:15,025 :: Exception in callback BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))
handle: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 510, in _sock_connect_cb
    fut.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
[ERROR]  asyncio 2020-10-02 09:40:16,317 :: Exception in callback BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))
handle: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...8.0.4', 9000)>, ('172.18.0.4', 9000))>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 510, in _sock_connect_cb
    fut.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
    handle = self._ready.popleft()
IndexError: pop from an empty deque
```

I guess this is now more of a problem with the way django >=3.1  and particularly django-channels is dealing with the event loop. Do you have by any chance quick thoughts on this? Is there a way to get the django "superpowered" event loop instead of the asyncio one?

Anyway will mark this bug report as resolved as it is cleary not xarrays issue.
Thanks a lot !

**Comment by jhnnsrs** [comment] 2020-10-02 15:58
Okay. That was too fast. Wasn't able to get the django implementation running, so I setup a testing environment with a docker composition running minio and a python3.8 based container with the libraries (repo attached). The setup runs fine for dask arrays of size (1024,1024,8,2,1) but causes the same asyncio problematic at (1024,1024,10,2,1) (tested with random arrays)

https://github.com/jhnnsrs/s3fs_bugreport

**Comment by martindurant** [comment] 2020-10-02 15:59
Thanks for the digging, I'll look into it

**Comment by martindurant** [comment] 2020-10-02 16:59
I have reproduced it locally (also with moto). Indeed, many threads are trying to stall the event loop at once. This will take a little finesse.

**Comment by martindurant** [comment] 2020-10-06 13:55
Can you confirm that this works ok with fsspec and s3fs master?

**Comment by jhnnsrs** [comment] 2020-10-06 15:27
Confirmed! Works like a charm. Went up all the way to (1024,1024,100,3,1) without any issues. Thanks for the fast fix! 👍

**Comment by martindurant** [comment] 2020-10-06 15:30
That's a lot of data!

**Comment by rabernat** [comment] 2020-10-06 15:40
@jhnnsrs: just a tip based on my own experience. In the code above, you are not specifying any chunks explicitly. The default is then to let zarr choose the chunk sizes. Zarr's default chunks are usually much smaller than what is optimal with cloud storage. I would recommend you explicitly chunk you array and aim for chunks around 100 MB.

Closing this as it appears to be fixed by @martindurant's quick response in fsspec / s3fs.

**Closed by rabernat** 2020-10-06 15:40 UTC

**Comment by forman** [comment] 2020-12-04 11:18
I'm still suffering from `IndexError: pop from an empty deque`. Can somebody tell me which `s3fs` version to use after fix by @martindurant?

Here are my relevant packages:

	# Name                    Version                   Build  Channel
	aiobotocore               0.10.3                     py_0    conda-forge
	aiohttp                   3.7.3            py39hb82d6ee_0    conda-forge
	botocore                  1.12.91                    py_0    conda-forge
	dask                      2.30.0                     py_0    conda-forge
	dask-core                 2.30.0                     py_0    conda-forge
	distributed               2.30.1           py39hcbf5309_0    conda-forge
	fsspec                    0.8.4                      py_0    conda-forge
	python                    3.9.0           h7840368_5_cpython    conda-forge
	s3fs                      0.5.1                      py_0    conda-forge
	xarray                    0.16.2             pyhd8ed1ab_0    conda-forge
	zarr                      2.5.0                      py_0    conda-forge

Thanks in advance!

**Comment by martindurant** [comment] 2020-12-07 14:39
Please try with fsspec master.
